// Implementation of the wasmtime-generated `host::Host` trait on `HostState`.
// This is the sole WASM↔core bridge. Mode dispatch (live vs
// replay) is done inside each method by matching `self.mode`.
//
// The trait is generated by `wasmtime::component::bindgen!` from
// `wit/loom-surface.wit::interface host`. The generated types are in
// `crate::wit_type_marshaller::loom_surface_bindings::loom::surface::`.
//
// NOTE: Return types mirror WIT definitions exactly (no wasmtime::Result
// wrapper). Methods that cannot propagate errors (clock_now, rng_next_u64)
// panic on internal failure — this produces a guest trap.
//
// wasmtime 44: `async: true` was removed from bindgen!; imports now use
// RPITIT (`impl Future + Send`). #[async_trait] is incompatible with the
// generated trait. Each method does its sync work up-front and returns a
// single `async move { ... }` block to avoid heterogeneous return types.

use super::host_function_table::HostState;
use crate::wit_type_marshaller::loom_surface_bindings::loom::surface::{
    host::Host,
    types::{
        ContentRef, EvaluateResult, HostError, Instant, LogLevel, NavigateResult, NetReq, NetResp,
        Receipt,
    },
};
use crate::wit_type_marshaller::Mode;
use loom_core::content_store::ContentRef as CoreContentRef;
use loom_core::vault::NetRequest;
use loom_shared::error_format::LoomErrorCode;
use std::sync::Arc;

// Convert WIT ContentRef → loom-core ContentRef
fn wit_ref_to_core(r: ContentRef) -> CoreContentRef {
    CoreContentRef {
        sha256: r.sha256,
        size_bytes: r.size,
    }
}

// Convert loom-core ContentRef → WIT ContentRef
fn core_ref_to_wit(r: CoreContentRef) -> ContentRef {
    ContentRef {
        sha256: r.sha256,
        size: r.size_bytes,
    }
}

// Convert a LoomError → WIT HostError (generated, string payload)
fn loom_to_wit_error(err: loom_shared::error_format::LoomError) -> HostError {
    let msg = err.message.clone();
    match err.code {
        LoomErrorCode::BudgetExceeded | LoomErrorCode::BudgetRateLimited => {
            HostError::BudgetExceeded(msg)
        }
        LoomErrorCode::VaultRejection
        | LoomErrorCode::VaultGrantExpired
        | LoomErrorCode::VaultGrantRevoked
        | LoomErrorCode::VaultUnknownLabel => HostError::VaultRejection(msg),
        LoomErrorCode::ShimFailure
        | LoomErrorCode::ShimTimeout
        | LoomErrorCode::ShimBreakerOpen => HostError::ShimFailure(msg),
        LoomErrorCode::StoreIntegrityFailed => HostError::StoreIntegrityFailed(msg),
        _ => HostError::Internal(msg),
    }
}

impl Host for HostState {
    // --- Determinism sources ---

    fn clock_now(&mut self) -> impl ::core::future::Future<Output = Instant> + Send {
        let ms = match self.mode {
            Mode::Live => self.determinism.clock_now(),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_clock().expect("replay clock underflow")
            }
        };
        async move { Instant { epoch_ms: ms } }
    }

    fn rng_next_u64(&mut self) -> impl ::core::future::Future<Output = u64> + Send {
        let val = match self.mode {
            Mode::Live => self.determinism.rng_next(),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_rng().expect("replay rng underflow")
            }
        };
        async move { val }
    }

    // --- Content store ---

    fn blob_put(
        &mut self,
        bytes: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<ContentRef, HostError>> + Send {
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "blob_put not allowed in replay mode".to_owned(),
            ))
        } else {
            match self.core.content_store.put(&bytes) {
                Ok(r) => Ok(core_ref_to_wit(r)),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    fn blob_get(
        &mut self,
        r: ContentRef,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        let result = match self.core.content_store.get(&wit_ref_to_core(r)) {
            Ok(bytes) => Ok(bytes),
            Err(e) => Err(loom_to_wit_error(e)),
        };
        async move { result }
    }

    // --- Network (vault-mediated; HARD invariant) ---

    fn net_request(
        &mut self,
        req: NetReq,
    ) -> impl ::core::future::Future<Output = Result<NetResp, HostError>> + Send {
        // Do all sync work (incl. vault substitution) before the async block so
        // the returned future holds only Send types and does not borrow self.
        let maybe_core_req: Result<NetRequest, HostError> = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "net_request not allowed in replay mode".to_owned(),
            ))
        } else {
            let mut core_req = NetRequest {
                url: req.url.clone(),
                method: req.method.clone(),
                headers: req.headers.iter().cloned().collect(),
                body: req.body.clone(),
                origin: req.url.clone(),
                scopes: Vec::new(),
            };
            // Vault credential substitution (grant_id "default" for now)
            let _ = self.core.vault.substitute(
                loom_core::vault::GrantId("default".to_owned()),
                &mut core_req,
            );
            Ok(core_req)
        };

        async move {
            let core_req = maybe_core_req?;
            // Perform the actual HTTP request via reqwest
            let resp = do_http_request(core_req)
                .await
                .map_err(HostError::Internal)?;

            // HARD invariant: strip Authorization from response headers
            let headers: Vec<(String, String)> = resp
                .headers
                .iter()
                .filter(|(k, _)| k.to_lowercase() != "authorization")
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();

            Ok(NetResp {
                status: resp.status,
                headers,
                body: resp.body,
            })
        }
    }

    // --- Vault (v0.9.6 web-cookie-injection grant resolution) ---

    fn vault_substitute_cookies(
        &mut self,
        grant_id: String,
        session_id: String,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use loom_core::manifest_writer::manifest_writer::SessionId;
        use loom_core::vault::GrantId;
        // Replay mode: refuse. Cookie values in replay must be supplied
        // externally via `replay_cookie_values` (§5), not pulled from the
        // live vault. This keeps replay self-contained.
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "vault_substitute_cookies not allowed in replay mode".to_owned(),
            ))
        } else {
            match self
                .core
                .vault
                .substitute_cookies(GrantId(grant_id), SessionId(session_id))
            {
                // Zeroizing<Vec<u8>> → Vec<u8>. The original Zeroizing
                // wrapper drops here, wiping its backing buffer (per the
                // v0.9.5 contract that raw cookie values are wiped in
                // daemon memory). The non-zeroizing copy below crosses
                // the WIT boundary into the WASM guest. The proper
                // through-boundary heap-wipe path is the §10 hardening
                // (separate tier).
                Ok(zeroized) => Ok(zeroized.to_vec()),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    // --- Out-of-process shim bridge ---

    fn shim_call(
        &mut self,
        shim_id: String,
        msg: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use crate::shim_manager::ShimId;
        // Namespace the shim id by the active session so each session
        // gets its own subprocess (reuse falls out: same
        // session_id → same effective ShimId → cached ShimProcess).
        let session_id = self.session_id.0.clone();
        let effective_id = ShimId(format!("{}:{}", shim_id, session_id));
        let shim_manager = self.shim_manager.clone();
        let session_id_for_register = session_id.clone();
        let raw_shim_id_for_register = shim_id.clone();
        // Capture profile + downloads_dir for env-var
        // injection at lazy-register time. Cloned out of `&mut self` so
        // the async block can move them.
        let profile_for_register = self.profile.clone();
        let downloads_dir_for_register = self.downloads_dir.clone();

        let maybe_call: Result<
            (ShimId, Vec<u8>, Arc<crate::shim_manager::ShimManager>),
            HostError,
        > = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "shim_call not allowed in replay mode".to_owned(),
            ))
        } else {
            Ok((effective_id.clone(), msg, shim_manager))
        };

        async move {
            match maybe_call {
                Err(e) => Err(e),
                Ok((effective_id, msg, shim_manager)) => {
                    // Lazy-register on first call. The daemon (L12) is
                    // expected to provide a template ShimConfig at
                    // construction time keyed by the bare shim name
                    // (e.g. "chromium"); we clone-and-namespace it here.
                    if !shim_manager.is_registered(&effective_id) {
                        if let Some(template) = shim_manager
                            .configs
                            .get(&ShimId(raw_shim_id_for_register.clone()))
                            .map(|c| c.clone())
                        {
                            let mut config = template;
                            // Per-session user-data-dir override.
                            let dir = std::env::temp_dir()
                                .join(format!("loom-chromium-{}", session_id_for_register));
                            config.env.push((
                                "LOOM_SHIM_USER_DATA_DIR".into(),
                                dir.display().to_string(),
                            ));
                            // Inject profile + downloads_dir env vars so the
                            // shim's CDP bootstrap can send
                            // `Browser.setDownloadBehavior(allowAndName,
                            // downloadPath=<dir>)` at startup. Confines
                            // Chromium downloads to the session-scoped dir.
                            if profile_for_register == "safe" {
                                config.env.push(("LOOM_SHIM_PROFILE".into(), "safe".into()));
                                match &downloads_dir_for_register {
                                    Some(d) => {
                                        config.env.push((
                                            "LOOM_SHIM_DOWNLOADS_DIR".into(),
                                            d.display().to_string(),
                                        ));
                                    }
                                    None => {
                                        // INVARIANT VIOLATION (mirror of the
                                        // navigate_execute path below) —
                                        // safe profile sessions must always
                                        // have downloads_dir per
                                        // LocalSessionManager::create.
                                        tracing::error!(
                                            session_id = %session_id_for_register,
                                            "safe-profile invariant: safe profile session has no \
                                             downloads_dir; Chromium download confinement DISABLED \
                                             for this shim"
                                        );
                                    }
                                }
                            }
                            shim_manager.register(effective_id.clone(), config);
                        } else {
                            return Err(HostError::ShimFailure(format!(
                                "no template config registered for shim {raw_shim_id_for_register}"
                            )));
                        }
                    }
                    match shim_manager.send(effective_id, msg).await {
                        Ok(bytes) => Ok(bytes),
                        Err(e) => Err(loom_to_wit_error(e)),
                    }
                }
            }
        }
    }

    // --- Logging and receipts (side-effect free from host perspective) ---

    fn log_emit(
        &mut self,
        level: LogLevel,
        msg: String,
        fields: Vec<(String, String)>,
    ) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = (level, msg, fields);
        // Route through HostObservability in the full implementation.
        async move {}
    }

    fn receipt_emit(&mut self, r: Receipt) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = r;
        // receipt_emit is a no-op for now: navigate receipt fields are
        // returned directly from navigate_execute. Surface-driven
        // receipt emission lands in a follow-up.
        async move {}
    }

    // --- Typed navigate-execute host function ---

    fn navigate_execute(
        &mut self,
        action_id: String,
        url: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<NavigateResult, HostError>> + Send {
        use crate::shim_manager::ShimId;

        // Do ALL sync work up front so the returned future holds only owned
        // Send types (same pattern as net_request / shim_call).
        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let content_store = self.core.content_store.clone();
        let determinism = self.determinism.clone();
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        // Compute affirmative wire form. The session
        // stores the negative-form `no_blocklist`; the wire carries the
        // affirmative `blocklist_enabled`. Inverting once at this seam
        // makes wire / log dumps directly readable.
        let blocklist_enabled = !self.no_blocklist;
        let manifest_writer = self.core.manifest_writer.clone();
        let session_id_for_audit = self.session_id.clone();
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);
        // Same env-var contract as `shim_call`. Captured
        // here for the lazy-register branch below.
        let profile_for_register = self.profile.clone();
        let downloads_dir_for_register = self.downloads_dir.clone();

        // Resolve effective shim ID and lazy-register if needed.
        // ALL sync work (including error cases) is collected into `maybe_id`
        // so the function returns a single `async move` block (RPITIT contract:
        // exactly one anonymous future type per function).
        let maybe_id: Result<ShimId, HostError> = if self.mode
            == crate::wit_type_marshaller::Mode::Replay
        {
            Err(HostError::Internal(
                "navigate_execute not allowed in replay mode".to_owned(),
            ))
        } else {
            let effective_id = ShimId(format!("chromium:{}", session_id_str));
            if !shim_manager.is_registered(&effective_id) {
                match shim_manager
                    .configs
                    .get(&ShimId("chromium".to_owned()))
                    .map(|c| c.clone())
                {
                    Some(mut config) => {
                        let dir =
                            std::env::temp_dir().join(format!("loom-chromium-{}", session_id_str));
                        config
                            .env
                            .push(("LOOM_SHIM_USER_DATA_DIR".into(), dir.display().to_string()));
                        // Same env-var contract as
                        // `shim_call`. The shim's CDP bootstrap reads these
                        // and sends Browser.setDownloadBehavior(allowAndName,
                        // downloadPath=$DIR) — Chromium then confines all
                        // downloads to the session-scoped dir. The
                        // Browser.downloadWillBegin visibility handler is
                        // a deferred follow-up; not implemented today.
                        if profile_for_register == "safe" {
                            config.env.push(("LOOM_SHIM_PROFILE".into(), "safe".into()));
                            match &downloads_dir_for_register {
                                Some(d) => {
                                    config.env.push((
                                        "LOOM_SHIM_DOWNLOADS_DIR".into(),
                                        d.display().to_string(),
                                    ));
                                }
                                None => {
                                    // INVARIANT VIOLATION: safe profile
                                    // sessions always have downloads_dir
                                    // (LocalSessionManager::create
                                    // populates it). If we land here, the
                                    // session was created via a path that
                                    // skipped the dir creation — Chromium
                                    // download confinement is silently
                                    // disabled.
                                    tracing::error!(
                                        session_id = %session_id_str,
                                        "safe-profile invariant: safe profile session has no downloads_dir; \
                                         Chromium download confinement DISABLED for this shim"
                                    );
                                }
                            }
                        }
                        shim_manager.register(effective_id.clone(), config);
                        Ok(effective_id)
                    }
                    None => Err(HostError::ShimFailure(
                        "no template config registered for shim chromium".to_owned(),
                    )),
                }
            } else {
                Ok(effective_id)
            }
        };

        async move {
            let effective_id = maybe_id?;

            // target_id = 0 → shim's PageNavigate handler lazy-spawns a
            // target via TargetManager::create_new_target, threading the
            // seed/epoch_ms into the determinism JS injection.
            let outcome = shim_manager
                .send_navigate(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    url.clone(),
                    budget_ms,
                    seed,
                    epoch_ms,
                    blocklist_enabled,
                )
                .await
                .map_err(loom_to_wit_error)?;

            // Every blocked sub-resource becomes a
            // typed audit entry in the manifest hash chain. JCS sorts
            // keys lexicographically; do not rely on declaration order.
            // Adding a new field requires re-verifying canonical output.
            for blocked in &outcome.blocked_events {
                let canonical = serde_jcs::to_vec(&serde_json::json!({
                    "matched_pattern": blocked.matched_pattern,
                    "reason": blocked.reason,
                    "url": blocked.url,
                }))
                .unwrap_or_default();
                if let Err(e) = manifest_writer.append_audit(
                    session_id_for_audit.clone(),
                    loom_core::manifest_writer::AuditKind::BlockedUrl,
                    canonical,
                ) {
                    tracing::warn!(
                        session = %session_id_for_audit.0,
                        url = blocked.url.as_str(),
                        error = %e,
                        "failed to append BlockedUrl audit entry"
                    );
                }
            }

            // Surface typed network failures as a typed HostError. Order matters:
            //   1. HTTP 4xx/5xx response: shim's CDP handler appends a
            //      `Network.responseReceived`-derived event whose
            //      `status` is the document's HTTP status. Prefer this
            //      over a paired transport-style error_reason because
            //      Chromium emits ERR_HTTP_RESPONSE_CODE_FAILURE alongside
            //      a 4xx/5xx responseReceived for empty-body responses
            //      (e.g. httpbin /status/404 + /status/500). Surfacing
            //      the actual `status_code` is more actionable than the
            //      `network_error: ERR_HTTP_RESPONSE_CODE_FAILURE` form.
            //   2. Transport-layer failure (DNS / connect-refused / TLS):
            //      shim pushes a `LoomNetworkEvent` with `error_reason`
            //      from `Network.loadingFailed` OR from
            //      `extract_nav_error_text(Page.navigate response)`.
            // The HTTP-first order is safe: DNS / connect-refused / TLS
            // never produce a status>=400 responseReceived (the
            // connection didn't carry an HTTP response), so they fall
            // through to the transport branch as before.
            // P0: the shim has captured the
            // `Network.responseReceived` events for this navigate even when
            // the navigate is about to surface as a typed error. Hoist the
            // structured JSON form once so the typed-error detail can carry
            // `_network_events` through to session_executor → ReceiptBuilder
            // → marshaller → ReceiptPayload, ensuring HAR export covers
            // failed navigates (4xx + transport errors).
            let network_events_value = serde_json::to_value(&outcome.network_events)
                .unwrap_or_else(|_| serde_json::Value::Array(Vec::new()));

            if let Some(ev) = outcome.network_events.iter().find(|e| e.status >= 400) {
                let detail = serde_json::json!({
                    "kind": "http_status",
                    "url": url,
                    "status_code": ev.status,
                    // P0: see comment above; carries the captured network
                    // events through to the typed-error receipt for HAR.
                    "_network_events": network_events_value,
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }
            if let Some(ev) = outcome
                .network_events
                .iter()
                .find(|e| e.error_reason.is_some())
            {
                let kind = ev.error_kind.as_deref().unwrap_or("network_error");
                let chromium_error = ev.error_reason.as_deref().unwrap_or("unknown");
                let detail = serde_json::json!({
                    "kind": kind,
                    "url": url, // navigate target
                    "chromium_error": chromium_error,
                    // P0: internal plumbing — stripped by session_executor before
                    // landing in receipt.error_details (leading underscore signals
                    // "not operator-facing").
                    "_network_events": network_events_value.clone(),
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }

            // Store dom_bytes and screenshot_bytes in ContentStore.
            let dom_ref = content_store
                .put(&outcome.dom_bytes)
                .map_err(loom_to_wit_error)?;
            let ss_ref = content_store
                .put(&outcome.screenshot_bytes)
                .map_err(loom_to_wit_error)?;

            // Session-monotonic timestamp from DeterminismHarness.
            let emitted_at_ms = determinism.clock_now();

            // Serialize network events as JSON Vec<LoomNetworkEvent>.
            let side_effects_json = serde_json::to_vec(&outcome.network_events).unwrap_or_default();

            // Serialize console_lines verbatim
            // (current stub returns Vec::new() until shim console capture lands).
            let console_lines_json = serde_json::to_vec(&outcome.console_lines).unwrap_or_default();

            // Aggregate NetworkSummary from captured events. Errors counted
            // as HTTP 4xx/5xx OR transport failures (`error_reason.is_some()`).
            let network_summary = loom_core::receipt_builder::receipt_builder::NetworkSummary {
                total_count: outcome.network_events.len() as u64,
                total_bytes: outcome
                    .network_events
                    .iter()
                    .map(|e| e.response_bytes)
                    .sum(),
                error_count: outcome
                    .network_events
                    .iter()
                    .filter(|e| e.status >= 400 || e.error_reason.is_some())
                    .count() as u64,
            };
            let network_summary_json = serde_json::to_vec(&network_summary).unwrap_or_default();

            Ok(NavigateResult {
                url: outcome.url,
                final_url: outcome.final_url,
                title: outcome.page_title,
                status_code: outcome.status_code as u32,
                dom_snapshot_hash: dom_ref.sha256,
                screenshot_after_hash: ss_ref.sha256,
                console_count: outcome.console_lines.len() as u64,
                network_count: outcome.network_events.len() as u64,
                side_effects_json,
                emitted_at_ms,
                console_lines_json,
                network_summary_json,
            })
        }
    }

    // --- Typed evaluate-execute host function ---

    fn evaluate_execute(
        &mut self,
        action_id: String,
        expression: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<EvaluateResult, HostError>> + Send {
        use crate::shim_manager::ShimId;

        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let content_store = self.core.content_store.clone();
        let determinism = self.determinism.clone();
        // Capture seed + epoch_ms so send_evaluate can do a lazy
        // SpawnTarget under the same per-session determinism context as
        // navigate_execute. Without this, evaluate-without-prior-navigate
        // routes to the bootstrap about:blank context where Date.now /
        // Math.random leak real values.
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);

        // Resolve effective shim ID and lazy-register if needed (same
        // pattern as navigate_execute).
        let maybe_id: Result<ShimId, HostError> = if self.mode
            == crate::wit_type_marshaller::Mode::Replay
        {
            Err(HostError::Internal(
                "evaluate_execute not allowed in replay mode".to_owned(),
            ))
        } else {
            let effective_id = ShimId(format!("chromium:{}", session_id_str));
            if !shim_manager.is_registered(&effective_id) {
                match shim_manager
                    .configs
                    .get(&ShimId("chromium".to_owned()))
                    .map(|c| c.clone())
                {
                    Some(mut config) => {
                        let dir =
                            std::env::temp_dir().join(format!("loom-chromium-{}", session_id_str));
                        config
                            .env
                            .push(("LOOM_SHIM_USER_DATA_DIR".into(), dir.display().to_string()));
                        shim_manager.register(effective_id.clone(), config);
                        Ok(effective_id)
                    }
                    None => Err(HostError::ShimFailure(
                        "no template config registered for shim chromium".to_owned(),
                    )),
                }
            } else {
                Ok(effective_id)
            }
        };

        async move {
            let effective_id = maybe_id?;

            // target_id = 0 (current stub) — send_evaluate will lazy-spawn
            // the determinism-injected target via SpawnTarget before
            // dispatching the actual Runtime.evaluate.
            let outcome = shim_manager
                .send_evaluate(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    expression,
                    budget_ms,
                    seed,
                    epoch_ms,
                )
                .await
                .map_err(loom_to_wit_error)?;

            // Page-side throw → typed shaped error.
            if let Some(ex) = outcome.exception {
                let detail = serde_json::json!({
                    "kind": "js_throw",
                    "exception": ex.message,
                    "line": ex.line,
                    "column": ex.column,
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }

            // Success path: convert CBOR result → canonical-JSON.
            let cbor_value = outcome.result.ok_or_else(|| {
                HostError::Internal("evaluate: no result and no exception".into())
            })?;
            let json_value = cbor_value_to_json(cbor_value)?;
            let canonical_json = serde_jcs::to_string(&json_value).map_err(|e| {
                HostError::Internal(format!("evaluate: canonical-JSON serialization: {e}"))
            })?;

            // Session-monotonic timestamp.
            let emitted_at_ms = determinism.clock_now();

            // > 64KB → offload to content store.
            const TRUNCATION_THRESHOLD: usize = 65_536;
            if canonical_json.len() > TRUNCATION_THRESHOLD {
                let cref = content_store
                    .put(canonical_json.as_bytes())
                    .map_err(loom_to_wit_error)?;
                Ok(EvaluateResult {
                    return_value_json: None,
                    return_value_blob_ref: Some(core_ref_to_wit(cref)),
                    emitted_at_ms,
                })
            } else {
                Ok(EvaluateResult {
                    return_value_json: Some(canonical_json),
                    return_value_blob_ref: None,
                    emitted_at_ms,
                })
            }
        }
    }
}

/// Convert a `ciborium::value::Value` (CDP `Runtime.evaluate.result.value`)
/// to a `serde_json::Value` suitable for canonical-JSON via `serde_jcs`.
///
/// Per  the wire bans IEEE-754 floats; numeric values
/// (integers and floats both) are emitted as canonical-JSON strings.
/// Non-representable CBOR (Bytes, Tag, non-string map keys) returns a
/// shaped `HostError::ShimFailure` so the caller surfaces a clean error
/// receipt rather than panicking the daemon (council Q8 policy).
fn cbor_value_to_json(v: ciborium::value::Value) -> Result<serde_json::Value, HostError> {
    use ciborium::value::Value;
    match v {
        Value::Null => Ok(serde_json::Value::Null),
        Value::Bool(b) => Ok(serde_json::Value::Bool(b)),
        Value::Integer(i) => Ok(serde_json::Value::String(format!("{}", i128::from(i)))),
        Value::Float(f) => {
            // numerics on the wire as strings. NaN /
            // Infinity / -Infinity round-trip as their literal IEEE-754
            // names; finite floats use Rust's default formatter (which
            // is round-trip-safe for f64).
            let s = if f.is_nan() {
                "NaN".to_string()
            } else if f.is_infinite() {
                if f.is_sign_negative() {
                    "-Infinity".to_string()
                } else {
                    "Infinity".to_string()
                }
            } else {
                format!("{f}")
            };
            Ok(serde_json::Value::String(s))
        }
        Value::Text(s) => Ok(serde_json::Value::String(s)),
        Value::Array(a) => {
            let mut out = Vec::with_capacity(a.len());
            for elem in a {
                out.push(cbor_value_to_json(elem)?);
            }
            Ok(serde_json::Value::Array(out))
        }
        Value::Map(m) => {
            // Q8: non-string keys → shaped error, not panic.
            let mut obj = serde_json::Map::with_capacity(m.len());
            for (k, val) in m {
                let key = match k {
                    Value::Text(s) => s,
                    _ => {
                        let detail = serde_json::json!({
                            "kind": "cbor_unrepresentable",
                            "reason": "non_string_map_key",
                        })
                        .to_string();
                        return Err(HostError::ShimFailure(detail));
                    }
                };
                obj.insert(key, cbor_value_to_json(val)?);
            }
            Ok(serde_json::Value::Object(obj))
        }
        Value::Bytes(_) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "bytes",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        Value::Tag(_, _) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "tag",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        _ => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "unknown_cbor_variant",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
    }
}

/// Perform a real HTTP request using reqwest (pure-Rust, rustls-tls).
/// Returns a loom-core NetResp on success or an error string on failure.
async fn do_http_request(req: NetRequest) -> Result<loom_core::vault::NetResp, String> {
    let client = reqwest::Client::builder()
        .use_rustls_tls()
        .build()
        .map_err(|e| e.to_string())?;

    let method = reqwest::Method::from_bytes(req.method.as_bytes()).map_err(|e| e.to_string())?;
    let mut rb = client.request(method, &req.url);
    for (k, v) in &req.headers {
        rb = rb.header(k.as_str(), v.as_str());
    }
    if !req.body.is_empty() {
        rb = rb.body(req.body.clone());
    }

    let response = rb.send().await.map_err(|e| e.to_string())?;
    let status = response.status().as_u16();
    let headers: std::collections::BTreeMap<String, String> = response
        .headers()
        .iter()
        .map(|(k, v)| (k.as_str().to_owned(), v.to_str().unwrap_or("").to_owned()))
        .collect();
    let body = response.bytes().await.map_err(|e| e.to_string())?.to_vec();

    Ok(loom_core::vault::NetResp {
        status,
        headers,
        body,
    })
}
