// Implementation of the wasmtime-generated `host::Host` trait on `HostState`.
// This is the sole WASM↔core bridge. Mode dispatch (live vs
// replay) is done inside each method by matching `self.mode`.
//
// The trait is generated by `wasmtime::component::bindgen!` from
// `wit/loom-surface.wit::interface host`. The generated types are in
// `crate::wit_type_marshaller::loom_surface_bindings::loom::surface::`.
//
// NOTE: Return types mirror WIT definitions exactly (no wasmtime::Result
// wrapper). Methods that cannot propagate errors (clock_now, rng_next_u64)
// panic on internal failure — this produces a guest trap.
//
// wasmtime 44: `async: true` was removed from bindgen!; imports now use
// RPITIT (`impl Future + Send`). #[async_trait] is incompatible with the
// generated trait. Each method does its sync work up-front and returns a
// single `async move { ... }` block to avoid heterogeneous return types.

use super::host_function_table::HostState;
use crate::network_offload::{offload_or_inline_network_entries, NetworkEntriesPayload};
use crate::wit_type_marshaller::loom_surface_bindings::loom::surface::{
    host::Host,
    types::{
        ContentRef, EvaluateResult, HostError, Instant, LogLevel, NavigateResult, NetReq, NetResp,
        Receipt, SetInputFilesResult, WaitResult,
    },
};
use crate::wit_type_marshaller::Mode;
use loom_core::content_store::ContentRef as CoreContentRef;
use loom_core::vault::NetRequest;
use loom_shared::error_format::LoomErrorCode;
use std::sync::Arc;

// Convert WIT ContentRef → loom-core ContentRef
fn wit_ref_to_core(r: ContentRef) -> CoreContentRef {
    CoreContentRef {
        sha256: r.sha256,
        size_bytes: r.size,
    }
}

// Convert loom-core ContentRef → WIT ContentRef
fn core_ref_to_wit(r: CoreContentRef) -> ContentRef {
    ContentRef {
        sha256: r.sha256,
        size: r.size_bytes,
    }
}

/// Resolve THIS navigation's main-document event from the shim's
/// attribution index. `navigate_execute`'s failure verdict (HTTP 4xx/5xx,
/// transport error) is scoped to this single event — an iframe's document
/// error or a stale prior-load event must never fail the whole navigate
/// (those events stay in `network_events` for observability). `None`
/// (no events, only iframe documents, or a legacy pre-field shim payload)
/// means no typed navigate failure is raised.
pub(super) fn main_document_event(
    events: &[loom_shared::navigate_outcome::LoomNetworkEvent],
    main_document_event_index: Option<u32>,
) -> Option<&loom_shared::navigate_outcome::LoomNetworkEvent> {
    main_document_event_index.and_then(|i| events.get(i as usize))
}

// Convert a LoomError → WIT HostError (generated, string payload)
fn loom_to_wit_error(err: loom_shared::error_format::LoomError) -> HostError {
    let msg = err.message.clone();
    match err.code {
        LoomErrorCode::BudgetExceeded | LoomErrorCode::BudgetRateLimited => {
            HostError::BudgetExceeded(msg)
        }
        LoomErrorCode::VaultRejection
        | LoomErrorCode::VaultGrantExpired
        | LoomErrorCode::VaultGrantRevoked
        | LoomErrorCode::VaultUnknownLabel => HostError::VaultRejection(msg),
        LoomErrorCode::ShimFailure
        | LoomErrorCode::ShimTimeout
        | LoomErrorCode::ShimBreakerOpen => HostError::ShimFailure(msg),
        LoomErrorCode::StoreIntegrityFailed => HostError::StoreIntegrityFailed(msg),
        _ => HostError::Internal(msg),
    }
}

impl HostState {
    /// Deterministic per-session virtual clock (ms) for receipt timestamps when
    /// determinism is enabled; `None` falls back to the harness clock. A pure
    /// function of the per-session `action_id` — no shared mutable state — so two
    /// independent same-seed runs produce byte-equal timestamps and concurrent
    /// sessions cannot bleed clock state into each other (the manifest-chain
    /// cross-run determinism property; see decisions D9).
    fn deterministic_clock_ms(&self) -> Option<u64> {
        if self.mode == Mode::Live && !self.no_determinism {
            Some(
                self.action_id
                    .saturating_mul(loom_core::determinism_harness::DETERMINISTIC_ACTION_DELTA_MS),
            )
        } else {
            None
        }
    }
}

impl Host for HostState {
    // --- Determinism sources ---

    fn clock_now(&mut self) -> impl ::core::future::Future<Output = Instant> + Send {
        let ms = match self.mode {
            Mode::Live => self
                .deterministic_clock_ms()
                .unwrap_or_else(|| self.determinism.clock_now()),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_clock().expect("replay clock underflow")
            }
        };
        async move { Instant { epoch_ms: ms } }
    }

    fn rng_next_u64(&mut self) -> impl ::core::future::Future<Output = u64> + Send {
        let val = match self.mode {
            Mode::Live => self.determinism.rng_next(),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_rng().expect("replay rng underflow")
            }
        };
        async move { val }
    }

    // --- Content store ---

    fn blob_put(
        &mut self,
        bytes: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<ContentRef, HostError>> + Send {
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "blob_put not allowed in replay mode".to_owned(),
            ))
        } else {
            match self.core.content_store.put(&bytes) {
                Ok(r) => Ok(core_ref_to_wit(r)),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    fn blob_get(
        &mut self,
        r: ContentRef,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        let result = match self.core.content_store.get(&wit_ref_to_core(r)) {
            Ok(bytes) => Ok(bytes),
            Err(e) => Err(loom_to_wit_error(e)),
        };
        async move { result }
    }

    fn record_screenshot(
        &mut self,
        cdp_response: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<ContentRef, HostError>> + Send {
        // Decode the CDP `{data: <base64-PNG>}` envelope into raw PNG bytes so
        // the content store holds a renderable image and the returned hash
        // resolves to an actual `image/png`.
        let result = match loom_shared::screenshot_decode::decode_cdp_screenshot(&cdp_response) {
            Ok(png) if !loom_shared::screenshot_decode::is_png(&png) => {
                // Decoded to something that isn't a PNG (empty/truncated/garbage).
                // Refuse to store it — a 0-byte or non-image blob would only
                // produce a dangling, unrenderable screenshot_after_hash.
                Err(HostError::ShimFailure(
                    "{\"kind\":\"screenshot_decode_failed\",\"reason\":\"decoded bytes are not a PNG\"}"
                        .to_string(),
                ))
            }
            Ok(png) => {
                if self.mode == Mode::Replay {
                    // Replay must NOT write to the content store, but must return
                    // the SAME hash live mode stored so the receipt's
                    // screenshot_after_hash is byte-identical. Derive it from the
                    // decoded bytes (the blob already exists in CAS from live).
                    Ok(ContentRef {
                        sha256: loom_core::content_store::sha256_hex(&png),
                        size: png.len() as u64,
                    })
                } else {
                    match self.core.content_store.put(&png) {
                        Ok(r) => Ok(core_ref_to_wit(r)),
                        Err(e) => Err(loom_to_wit_error(e)),
                    }
                }
            }
            Err(e) => Err(HostError::ShimFailure(format!(
                "{{\"kind\":\"screenshot_decode_failed\",\"reason\":\"{e}\"}}"
            ))),
        };
        async move { result }
    }

    // --- Network (vault-mediated; HARD invariant) ---

    fn net_request(
        &mut self,
        req: NetReq,
    ) -> impl ::core::future::Future<Output = Result<NetResp, HostError>> + Send {
        // Do all sync work (incl. vault substitution) before the async block so
        // the returned future holds only Send types and does not borrow self.
        let maybe_core_req: Result<NetRequest, HostError> = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "net_request not allowed in replay mode".to_owned(),
            ))
        } else {
            let mut core_req = NetRequest {
                url: req.url.clone(),
                method: req.method.clone(),
                headers: req.headers.iter().cloned().collect(),
                authorization: None,
                body: req.body.clone(),
                origin: req.url.clone(),
                scopes: Vec::new(),
            };
            // Vault credential substitution (grant_id "default" for now).
            // The dispatching session scopes the grant lookup (NFR-DET-01:
            // grant ids are deterministic per session).
            let _ = self.core.vault.substitute(
                &self.session_id,
                loom_core::vault::GrantId("default".to_owned()),
                &mut core_req,
            );
            Ok(core_req)
        };

        async move {
            let core_req = maybe_core_req?;
            // Perform the actual HTTP request via reqwest
            let resp = do_http_request(core_req)
                .await
                .map_err(HostError::Internal)?;

            // HARD invariant: strip Authorization from response headers
            let headers: Vec<(String, String)> = resp
                .headers
                .iter()
                .filter(|(k, _)| k.to_lowercase() != "authorization")
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();

            Ok(NetResp {
                status: resp.status,
                headers,
                body: resp.body,
            })
        }
    }

    // --- Vault (v0.9.6 web-cookie-injection grant resolution) ---

    fn vault_substitute_cookies(
        &mut self,
        grant_id: String,
        session_id: String,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use loom_core::manifest_writer::manifest_writer::SessionId;
        use loom_core::vault::GrantId;
        // Replay mode: refuse. Cookie values in replay must be supplied
        // externally via `replay_cookie_values` (§5), not pulled from the
        // live vault. This keeps replay self-contained.
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "vault_substitute_cookies not allowed in replay mode".to_owned(),
            ))
        } else {
            match self
                .core
                .vault
                .substitute_cookies(GrantId(grant_id), SessionId(session_id))
            {
                // Zeroizing<Vec<u8>> → Vec<u8>. The original Zeroizing
                // wrapper drops here, wiping its backing buffer (per the
                // v0.9.5 contract that raw cookie values are wiped in
                // daemon memory). The non-zeroizing copy below crosses
                // the WIT boundary into the WASM guest. The proper
                // through-boundary heap-wipe path is the §10 hardening
                // (separate tier).
                Ok(zeroized) => Ok(zeroized.to_vec()),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    // --- Out-of-process shim bridge ---

    fn shim_call(
        &mut self,
        shim_id: String,
        msg: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use crate::shim_manager::ShimId;
        // Namespace the shim id by the active session so each session
        // gets its own subprocess (reuse falls out: same
        // session_id → same effective ShimId → cached ShimProcess).
        let session_id = self.session_id.0.clone();
        let effective_id = ShimId(format!("{}:{}", shim_id, session_id));
        let shim_manager = self.shim_manager.clone();
        let session_id_for_register = session_id.clone();
        let raw_shim_id_for_register = shim_id.clone();
        // Capture profile + downloads_dir for env-var
        // injection at lazy-register time. Cloned out of `&mut self` so
        // the async block can move them.
        let profile_for_register = self.profile.clone();
        let downloads_dir_for_register = self.downloads_dir.clone();

        let maybe_call: Result<
            (ShimId, Vec<u8>, Arc<crate::shim_manager::ShimManager>),
            HostError,
        > = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "shim_call not allowed in replay mode".to_owned(),
            ))
        } else {
            Ok((effective_id.clone(), msg, shim_manager))
        };

        async move {
            match maybe_call {
                Err(e) => Err(e),
                Ok((effective_id, msg, shim_manager)) => {
                    // Lazy-register on first call. The daemon (L12) is
                    // expected to provide a template ShimConfig at
                    // construction time keyed by the bare shim name
                    // (e.g. "chromium"); we clone-and-namespace it here.
                    if !shim_manager.is_registered(&effective_id) {
                        if let Some(template) = shim_manager
                            .configs
                            .get(&ShimId(raw_shim_id_for_register.clone()))
                            .map(|c| c.clone())
                        {
                            let mut config = template;
                            // Per-session user-data-dir override.
                            let dir = std::env::temp_dir()
                                .join(format!("loom-chromium-{}", session_id_for_register));
                            config.env.push((
                                "LOOM_SHIM_USER_DATA_DIR".into(),
                                dir.display().to_string(),
                            ));
                            // Inject profile + downloads_dir env vars so the
                            // shim's CDP bootstrap can send
                            // `Browser.setDownloadBehavior(allowAndName,
                            // downloadPath=<dir>)` at startup. Confines
                            // Chromium downloads to the session-scoped dir.
                            if profile_for_register == "safe" {
                                config.env.push(("LOOM_SHIM_PROFILE".into(), "safe".into()));
                                match &downloads_dir_for_register {
                                    Some(d) => {
                                        config.env.push((
                                            "LOOM_SHIM_DOWNLOADS_DIR".into(),
                                            d.display().to_string(),
                                        ));
                                    }
                                    None => {
                                        // INVARIANT VIOLATION (mirror of the
                                        // navigate_execute path below) —
                                        // safe profile sessions must always
                                        // have downloads_dir per
                                        // LocalSessionManager::create.
                                        tracing::error!(
                                            session_id = %session_id_for_register,
                                            "safe-profile invariant: safe profile session has no \
                                             downloads_dir; Chromium download confinement DISABLED \
                                             for this shim"
                                        );
                                    }
                                }
                            }
                            shim_manager.register(effective_id.clone(), config);
                        } else {
                            return Err(HostError::ShimFailure(format!(
                                "no template config registered for shim {raw_shim_id_for_register}"
                            )));
                        }
                    }
                    match shim_manager.send(effective_id, msg).await {
                        Ok(bytes) => Ok(bytes),
                        Err(e) => Err(loom_to_wit_error(e)),
                    }
                }
            }
        }
    }

    // --- Logging and receipts (side-effect free from host perspective) ---

    fn log_emit(
        &mut self,
        level: LogLevel,
        msg: String,
        fields: Vec<(String, String)>,
    ) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = (level, msg, fields);
        // Route through HostObservability in the full implementation.
        async move {}
    }

    fn receipt_emit(&mut self, r: Receipt) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = r;
        // receipt_emit is a no-op for now: navigate receipt fields are
        // returned directly from navigate_execute. Surface-driven
        // receipt emission lands in a follow-up.
        async move {}
    }

    // --- Typed navigate-execute host function ---

    fn navigate_execute(
        &mut self,
        action_id: String,
        url: String,
        until: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<NavigateResult, HostError>> + Send {
        use crate::shim_manager::ShimId;

        // Do ALL sync work up front so the returned future holds only owned
        // Send types (same pattern as net_request / shim_call).
        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let content_store = self.core.content_store.clone();
        let determinism = self.determinism.clone();
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        // Compute affirmative wire form. The session
        // stores the negative-form `no_blocklist`; the wire carries the
        // affirmative `blocklist_enabled`. Inverting once at this seam
        // makes wire / log dumps directly readable.
        let blocklist_enabled = !self.no_blocklist;
        // settle-capture (4b): per-session determinism toggle.
        let determinism_enabled = !self.no_determinism;
        let manifest_writer = self.core.manifest_writer.clone();
        let session_id_for_audit = self.session_id.clone();
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);
        // Same env-var contract as `shim_call`. Captured
        // here for the lazy-register branch below.
        let profile_for_register = self.profile.clone();
        let downloads_dir_for_register = self.downloads_dir.clone();

        // Resolve effective shim ID and lazy-register if needed.
        // ALL sync work (including error cases) is collected into `maybe_id`
        // so the function returns a single `async move` block (RPITIT contract:
        // exactly one anonymous future type per function).
        let maybe_id: Result<ShimId, HostError> = if self.mode
            == crate::wit_type_marshaller::Mode::Replay
        {
            Err(HostError::Internal(
                "navigate_execute not allowed in replay mode".to_owned(),
            ))
        } else {
            // The safe-profile env stays INLINE here (load-bearing
            // downloads_dir invariant) — the helper handles only the common
            // register core shared with evaluate / set_input_files. The shim's
            // CDP bootstrap reads LOOM_SHIM_PROFILE/LOOM_SHIM_DOWNLOADS_DIR and
            // sends Browser.setDownloadBehavior(allowAndName, downloadPath=$DIR)
            // so Chromium confines downloads to the session-scoped dir. The
            // Browser.downloadWillBegin visibility handler is a deferred
            // follow-up; not implemented today.
            register_chromium_shim_if_absent(&shim_manager, &session_id_str, |config| {
                if profile_for_register == "safe" {
                    config.env.push(("LOOM_SHIM_PROFILE".into(), "safe".into()));
                    match &downloads_dir_for_register {
                        Some(d) => {
                            config
                                .env
                                .push(("LOOM_SHIM_DOWNLOADS_DIR".into(), d.display().to_string()));
                        }
                        None => {
                            // INVARIANT VIOLATION: safe profile sessions always
                            // have downloads_dir (LocalSessionManager::create
                            // populates it). If we land here, the session was
                            // created via a path that skipped the dir creation
                            // — Chromium download confinement is silently
                            // disabled.
                            tracing::error!(
                                session_id = %session_id_str,
                                "safe-profile invariant: safe profile session has no downloads_dir; \
                                 Chromium download confinement DISABLED for this shim"
                            );
                        }
                    }
                }
            })
        };

        async move {
            let effective_id = maybe_id?;

            // target_id = 0 → shim's PageNavigate handler lazy-spawns a
            // target via TargetManager::create_new_target, threading the
            // seed/epoch_ms into the determinism JS injection.
            let outcome = shim_manager
                .send_navigate(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    url.clone(),
                    budget_ms,
                    seed,
                    epoch_ms,
                    blocklist_enabled,
                    until,
                    determinism_enabled,
                )
                .await
                .map_err(loom_to_wit_error)?;

            // Every blocked sub-resource becomes a
            // typed audit entry in the manifest hash chain. JCS sorts
            // keys lexicographically; do not rely on declaration order.
            // Adding a new field requires re-verifying canonical output.
            for blocked in &outcome.blocked_events {
                let canonical = serde_jcs::to_vec(&serde_json::json!({
                    "matched_pattern": blocked.matched_pattern,
                    "reason": blocked.reason,
                    "url": blocked.url,
                }))
                .unwrap_or_default();
                if let Err(e) = manifest_writer.append_audit(
                    session_id_for_audit.clone(),
                    loom_core::manifest_writer::AuditKind::BlockedUrl,
                    canonical,
                ) {
                    tracing::warn!(
                        session = %session_id_for_audit.0,
                        url = blocked.url.as_str(),
                        error = %e,
                        "failed to append BlockedUrl audit entry"
                    );
                }
            }

            // Surface typed network failures as a typed HostError, scoped to
            // THIS navigation's MAIN document only. The shim attributes each
            // Document event to a frame/loader and reports the main-document
            // event's index in `main_document_event_index`; an embedded
            // iframe's 4xx document response, a blocklist-failed iframe
            // document, or a stale/cancelled prior load must NOT fail the
            // whole navigate — those events stay in `network_events` for
            // observability only. Order matters:
            //   1. HTTP 4xx/5xx response: shim's CDP handler appends a
            //      `Network.responseReceived`-derived event whose
            //      `status` is the document's HTTP status. Prefer this
            //      over a paired transport-style error_reason because
            //      Chromium emits ERR_HTTP_RESPONSE_CODE_FAILURE alongside
            //      a 4xx/5xx responseReceived for empty-body responses
            //      (e.g. httpbin /status/404 + /status/500). Surfacing
            //      the actual `status_code` is more actionable than the
            //      `network_error: ERR_HTTP_RESPONSE_CODE_FAILURE` form.
            //      (The shim's `find_main_document_index` mirrors this
            //      HTTP-first preference when picking the main event.)
            //   2. Transport-layer failure (DNS / connect-refused / TLS):
            //      shim pushes a `LoomNetworkEvent` with `error_reason`
            //      from `Network.loadingFailed` OR from
            //      `extract_nav_error_text(Page.navigate response)`.
            // The HTTP-first order is safe: DNS / connect-refused / TLS
            // never produce a status>=400 responseReceived (the
            // connection didn't carry an HTTP response), so they fall
            // through to the transport branch as before.
            // P0: the shim has captured the
            // `Network.responseReceived` events for this navigate even when
            // the navigate is about to surface as a typed error. Hoist the
            // structured JSON form once so the typed-error detail can carry
            // `_network_events` through to session_executor → ReceiptBuilder
            // → marshaller → ReceiptPayload, ensuring HAR export covers
            // failed navigates (4xx + transport errors).
            let network_events_value = serde_json::to_value(&outcome.network_events)
                .unwrap_or_else(|_| serde_json::Value::Array(Vec::new()));
            let main_document_event =
                main_document_event(&outcome.network_events, outcome.main_document_event_index);

            if let Some(ev) = main_document_event.filter(|e| e.status >= 400) {
                let detail = serde_json::json!({
                    "kind": "http_status",
                    "url": url,
                    "status_code": ev.status,
                    // P0: see comment above; carries the captured network
                    // events through to the typed-error receipt for HAR.
                    "_network_events": network_events_value,
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }
            if let Some(ev) = main_document_event.filter(|e| e.error_reason.is_some()) {
                let kind = ev.error_kind.as_deref().unwrap_or("network_error");
                let chromium_error = ev.error_reason.as_deref().unwrap_or("unknown");
                let detail = serde_json::json!({
                    "kind": kind,
                    "url": url, // navigate target
                    "chromium_error": chromium_error,
                    // P0: internal plumbing — stripped by session_executor before
                    // landing in receipt.error_details (leading underscore signals
                    // "not operator-facing").
                    "_network_events": network_events_value.clone(),
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }

            // Store dom_bytes and screenshot_bytes in ContentStore.
            let dom_ref = content_store
                .put(&outcome.dom_bytes)
                .map_err(loom_to_wit_error)?;
            let ss_ref = content_store
                .put(&outcome.screenshot_bytes)
                .map_err(loom_to_wit_error)?;

            // Session-monotonic timestamp: deterministic per-session virtual
            // clock when determinism is on (cross-run byte-equal), else harness.
            let emitted_at_ms = self
                .deterministic_clock_ms()
                .unwrap_or_else(|| determinism.clock_now());

            // Serialize network events as JSON Vec<LoomNetworkEvent>.
            let side_effects_json = serde_json::to_vec(&outcome.network_events).unwrap_or_default();

            // Serialize console_lines verbatim
            // (current stub returns Vec::new() until shim console capture lands).
            let console_lines_json = serde_json::to_vec(&outcome.console_lines).unwrap_or_default();

            // Aggregate NetworkSummary from captured events. Errors counted
            // as HTTP 4xx/5xx OR transport failures (`error_reason.is_some()`).
            let network_summary = loom_core::receipt_builder::receipt_builder::NetworkSummary {
                total_count: outcome.network_events.len() as u64,
                total_bytes: outcome
                    .network_events
                    .iter()
                    .map(|e| e.response_bytes)
                    .sum(),
                error_count: outcome
                    .network_events
                    .iter()
                    .filter(|e| e.status >= 400 || e.error_reason.is_some())
                    .count() as u64,
            };
            let network_summary_json = serde_json::to_vec(&network_summary).unwrap_or_default();

            // Observational network-entries side-channel (NOT hash-chained) — the
            // serialize + ≥64KB offload-or-inline + fail-open degrade logic lives in
            // `crate::network_offload` (shared with `WasmHost::network_log`). This data
            // must NEVER fail a navigate, so a serialize/put error drops the list and
            // forces truncated=true rather than erroring.
            let (network_entries_payload, network_entries_truncated) =
                offload_or_inline_network_entries(
                    &*content_store,
                    &outcome.network_entries,
                    outcome.network_entries_truncated,
                    &session_id_str,
                );
            let (network_entries_json, network_entries_blob_ref) = match network_entries_payload {
                NetworkEntriesPayload::Inline(bytes) => (Some(bytes), None),
                NetworkEntriesPayload::Offloaded(cref) => (None, Some(core_ref_to_wit(cref))),
                NetworkEntriesPayload::Dropped => (None, None),
            };

            Ok(NavigateResult {
                url: outcome.url,
                final_url: outcome.final_url,
                title: outcome.page_title,
                status_code: outcome.status_code as u32,
                dom_snapshot_hash: dom_ref.sha256,
                screenshot_after_hash: ss_ref.sha256,
                console_count: outcome.console_lines.len() as u64,
                network_count: outcome.network_events.len() as u64,
                side_effects_json,
                emitted_at_ms,
                console_lines_json,
                network_summary_json,
                network_entries_json,
                network_entries_blob_ref,
                network_entries_truncated,
                // settle-capture: pass the shim's readiness verdict through.
                // These are NOT folded into outcome_hash (the guest excludes
                // them) — they are virtual-time-derived diagnostics.
                settle_until: outcome.settle_until,
                settle_outcome: outcome.settle_outcome,
                settle_ms: outcome.settle_ms,
                network_count_at_settle: outcome.network_count_at_settle,
            })
        }
    }

    // --- Typed wait-for-execute host function (settle-capture slice 2) ---
    fn wait_for_execute(
        &mut self,
        action_id: String,
        until: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<WaitResult, HostError>> + Send {
        use crate::shim_manager::ShimId;

        // ALL sync work up front so the future holds only owned Send types.
        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let determinism = self.determinism.clone();
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        // settle-capture (4b): per-session determinism toggle.
        let determinism_enabled = !self.no_determinism;
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);

        let maybe_id: Result<ShimId, HostError> =
            if self.mode == crate::wit_type_marshaller::Mode::Replay {
                Err(HostError::Internal(
                    "wait_for_execute not allowed in replay mode".to_owned(),
                ))
            } else {
                // wait_for never navigates or downloads, so it needs only the
                // common register core (no safe-profile downloads_dir env).
                register_chromium_shim_if_absent(&shim_manager, &session_id_str, |_config| {})
            };

        async move {
            let effective_id = maybe_id?;

            // target_id = 0 → resolves to the session's current target (the
            // shim's WaitFor handler runs after an idempotent SpawnTarget).
            let outcome = shim_manager
                .send_wait_for(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    until,
                    budget_ms,
                    seed,
                    epoch_ms,
                    determinism_enabled,
                )
                .await
                .map_err(loom_to_wit_error)?;

            // Session-monotonic timestamp from DeterminismHarness (like navigate).
            let emitted_at_ms = self
                .deterministic_clock_ms()
                .unwrap_or_else(|| determinism.clock_now());

            Ok(WaitResult {
                settle_until: outcome.settle_until,
                settle_outcome: outcome.settle_outcome,
                settle_ms: outcome.settle_ms,
                network_count_at_settle: outcome.network_count_at_settle,
                emitted_at_ms,
            })
        }
    }

    // --- Typed evaluate-execute host function ---

    fn evaluate_execute(
        &mut self,
        action_id: String,
        expression: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<EvaluateResult, HostError>> + Send {
        use crate::shim_manager::ShimId;

        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let content_store = self.core.content_store.clone();
        let determinism = self.determinism.clone();
        // Capture seed + epoch_ms so send_evaluate can do a lazy
        // SpawnTarget under the same per-session determinism context as
        // navigate_execute. Without this, evaluate-without-prior-navigate
        // routes to the bootstrap about:blank context where Date.now /
        // Math.random leak real values.
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        // settle-capture (4b): per-session determinism toggle.
        let determinism_enabled = !self.no_determinism;
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);

        // Resolve effective shim ID and lazy-register if needed (same
        // pattern as navigate_execute).
        let maybe_id: Result<ShimId, HostError> =
            if self.mode == crate::wit_type_marshaller::Mode::Replay {
                Err(HostError::Internal(
                    "evaluate_execute not allowed in replay mode".to_owned(),
                ))
            } else {
                register_chromium_shim_if_absent(&shim_manager, &session_id_str, |_config| {})
            };

        async move {
            let effective_id = maybe_id?;

            // target_id = 0 (current stub) — send_evaluate will lazy-spawn
            // the determinism-injected target via SpawnTarget before
            // dispatching the actual Runtime.evaluate.
            let outcome = shim_manager
                .send_evaluate(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    expression,
                    budget_ms,
                    seed,
                    epoch_ms,
                    determinism_enabled,
                )
                .await
                .map_err(loom_to_wit_error)?;

            // Page-side throw → typed shaped error.
            if let Some(ex) = outcome.exception {
                let detail = serde_json::json!({
                    "kind": "js_throw",
                    "exception": ex.message,
                    "line": ex.line,
                    "column": ex.column,
                })
                .to_string();
                return Err(HostError::ShimFailure(detail));
            }

            // Success path: convert CBOR result → canonical-JSON.
            let cbor_value = outcome.result.ok_or_else(|| {
                HostError::Internal("evaluate: no result and no exception".into())
            })?;
            let json_value = cbor_value_to_json(cbor_value)?;
            let canonical_json = serde_jcs::to_string(&json_value).map_err(|e| {
                HostError::Internal(format!("evaluate: canonical-JSON serialization: {e}"))
            })?;

            // Session-monotonic timestamp.
            let emitted_at_ms = self
                .deterministic_clock_ms()
                .unwrap_or_else(|| determinism.clock_now());

            // > 64KB → offload to content store.
            const TRUNCATION_THRESHOLD: usize = 65_536;
            if canonical_json.len() > TRUNCATION_THRESHOLD {
                let cref = content_store
                    .put(canonical_json.as_bytes())
                    .map_err(loom_to_wit_error)?;
                Ok(EvaluateResult {
                    return_value_json: None,
                    return_value_blob_ref: Some(core_ref_to_wit(cref)),
                    emitted_at_ms,
                })
            } else {
                Ok(EvaluateResult {
                    return_value_json: Some(canonical_json),
                    return_value_blob_ref: None,
                    emitted_at_ms,
                })
            }
        }
    }

    fn set_input_files_execute(
        &mut self,
        action_id: String,
        payload: Vec<u8>,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<SetInputFilesResult, HostError>> + Send {
        use crate::shim_manager::{SetInputFilesOutcome, ShimId};

        // The guest forwards the daemon-built canonical JSON
        // {"selector":..,"paths":[..]} verbatim (it has no JSON parser).
        // Parse it host-side. Malformed payload → Internal (should never
        // happen — the daemon builds it).
        #[derive(serde::Deserialize)]
        struct SetInputFilesPayload {
            selector: String,
            paths: Vec<String>,
        }
        let parsed: Result<SetInputFilesPayload, HostError> = serde_json::from_slice(&payload)
            .map_err(|e| HostError::Internal(format!("set_input_files: payload parse: {e}")));

        let session_id_str = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();
        let seed = self.seed;
        let epoch_ms = self.epoch_ms;
        // settle-capture (4b): per-session determinism toggle.
        let determinism_enabled = !self.no_determinism;
        let shim_session_id = shim_manager.shim_session_id_for(&session_id_str);

        // Resolve effective shim ID and lazy-register if needed (same
        // pattern as navigate_execute / evaluate_execute).
        let maybe_id: Result<ShimId, HostError> = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "set_input_files_execute not allowed in replay mode".to_owned(),
            ))
        } else {
            register_chromium_shim_if_absent(&shim_manager, &session_id_str, |_config| {})
        };

        async move {
            let effective_id = maybe_id?;
            let SetInputFilesPayload { selector, paths } = parsed?;
            // Paths are already validated + canonicalized daemon-side
            // (upload_guard). target_id = 0 → resolves to the session target,
            // same as send_evaluate.
            let outcome = shim_manager
                .send_set_input_files(
                    effective_id,
                    action_id,
                    shim_session_id,
                    0,
                    selector,
                    paths,
                    budget_ms,
                    seed,
                    epoch_ms,
                    determinism_enabled,
                )
                .await
                .map_err(loom_to_wit_error)?;

            match outcome {
                SetInputFilesOutcome::Ok { file_count } => Ok(SetInputFilesResult { file_count }),
                // Discrete typed wire kinds (plan-council FND#8) — NOT panics.
                SetInputFilesOutcome::SelectorNotFound => Err(HostError::ShimFailure(
                    serde_json::json!({"kind":"selector_not_found","verb":"set_input_files"})
                        .to_string(),
                )),
                SetInputFilesOutcome::NotAFileInput => Err(HostError::ShimFailure(
                    serde_json::json!({"kind":"not_a_file_input","verb":"set_input_files"})
                        .to_string(),
                )),
            }
        }
    }
}

/// Convert a `ciborium::value::Value` (CDP `Runtime.evaluate.result.value`)
/// to a `serde_json::Value` suitable for canonical-JSON via `serde_jcs`.
///
/// Per  the wire bans IEEE-754 floats; numeric values
/// (integers and floats both) are emitted as canonical-JSON strings.
/// Non-representable CBOR (Bytes, Tag, non-string map keys) returns a
/// shaped `HostError::ShimFailure` so the caller surfaces a clean error
/// receipt rather than panicking the daemon (council Q8 policy).
fn cbor_value_to_json(v: ciborium::value::Value) -> Result<serde_json::Value, HostError> {
    use ciborium::value::Value;
    match v {
        Value::Null => Ok(serde_json::Value::Null),
        Value::Bool(b) => Ok(serde_json::Value::Bool(b)),
        Value::Integer(i) => Ok(serde_json::Value::String(format!("{}", i128::from(i)))),
        Value::Float(f) => {
            // numerics on the wire as strings. NaN /
            // Infinity / -Infinity round-trip as their literal IEEE-754
            // names; finite floats use Rust's default formatter (which
            // is round-trip-safe for f64).
            let s = if f.is_nan() {
                "NaN".to_string()
            } else if f.is_infinite() {
                if f.is_sign_negative() {
                    "-Infinity".to_string()
                } else {
                    "Infinity".to_string()
                }
            } else {
                format!("{f}")
            };
            Ok(serde_json::Value::String(s))
        }
        Value::Text(s) => Ok(serde_json::Value::String(s)),
        Value::Array(a) => {
            let mut out = Vec::with_capacity(a.len());
            for elem in a {
                out.push(cbor_value_to_json(elem)?);
            }
            Ok(serde_json::Value::Array(out))
        }
        Value::Map(m) => {
            // Q8: non-string keys → shaped error, not panic.
            let mut obj = serde_json::Map::with_capacity(m.len());
            for (k, val) in m {
                let key = match k {
                    Value::Text(s) => s,
                    _ => {
                        let detail = serde_json::json!({
                            "kind": "cbor_unrepresentable",
                            "reason": "non_string_map_key",
                        })
                        .to_string();
                        return Err(HostError::ShimFailure(detail));
                    }
                };
                obj.insert(key, cbor_value_to_json(val)?);
            }
            Ok(serde_json::Value::Object(obj))
        }
        Value::Bytes(_) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "bytes",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        Value::Tag(_, _) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "tag",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        _ => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "unknown_cbor_variant",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
    }
}

// === SSRF guard (audit 2026-06-10: net_request is an unguarded SSRF
// primitive on the WIT trust boundary) ===
//
// `net_request` is a host primitive a (possibly compromised, per threat-model
// AB1) WASM guest can call directly from the daemon's network position. The
// guard below makes outbound HTTP from that primitive non-bypassable:
//
//   1. Scheme allowlist — only `http`/`https`.
//   2. DNS is resolved ONCE in the host (not by reqwest), every resolved
//      socket addr is checked against the blocked-range set, and the request
//      is pinned to those exact addrs via `resolve` so reqwest can never do a
//      second, unchecked lookup (the DNS-rebind window).
//   3. Auto-redirect is DISABLED; redirects are followed manually so the full
//      resolve+validate guard re-runs on every hop's `Location`.
//
// The blocked-range predicate lives in the pure, unit-tested
// `ip_is_blocked` / `validate_outbound_url` functions below.

use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};

/// Maximum redirect hops followed manually (matches reqwest's historical
/// default of 10).
const MAX_REDIRECT_HOPS: usize = 10;

/// Returns `true` for IPs a guest must never be able to reach: loopback,
/// private/RFC1918, link-local (incl. the 169.254.169.254 cloud-metadata
/// endpoint), unspecified, ULA (fc00::/7), IPv4-mapped/compat IPv6 of any of
/// the above, plus broadcast / documentation / benchmarking ranges. Checked
/// AFTER DNS resolution so a public hostname that resolves to an internal IP
/// (DNS rebind) is still rejected.
fn ip_is_blocked(ip: IpAddr) -> bool {
    match ip {
        IpAddr::V4(v4) => ipv4_is_blocked(v4),
        IpAddr::V6(v6) => {
            // Unwrap IPv4-MAPPED addresses (::ffff:a.b.c.d) so an attacker
            // can't smuggle 127.0.0.1 in as ::ffff:127.0.0.1. Note: we use
            // `to_ipv4_mapped` (not `to_ipv4`) on purpose — `to_ipv4` also
            // maps the deprecated IPv4-compatible form, which would turn ::1
            // into 0.0.0.1 and slip loopback past the v4 check.
            if let Some(mapped) = v6.to_ipv4_mapped() {
                return ipv4_is_blocked(mapped);
            }
            ipv6_is_blocked(v6)
        }
    }
}

fn ipv4_is_blocked(v4: Ipv4Addr) -> bool {
    let o = v4.octets();
    v4.is_loopback()            // 127.0.0.0/8
        || v4.is_private()      // 10/8, 172.16/12, 192.168/16
        || v4.is_link_local()  // 169.254/16 (incl. 169.254.169.254 metadata)
        || v4.is_unspecified() // 0.0.0.0
        || v4.is_broadcast()   // 255.255.255.255
        || v4.is_documentation()
        // 100.64.0.0/10 — carrier-grade NAT / shared address space.
        || (o[0] == 100 && (64..=127).contains(&o[1]))
        // 192.0.0.0/24 — IETF protocol assignments.
        || (o[0] == 192 && o[1] == 0 && o[2] == 0)
        // 198.18.0.0/15 — benchmarking.
        || (o[0] == 198 && (o[1] == 18 || o[1] == 19))
        // 240.0.0.0/4 — reserved (excludes the broadcast addr handled above).
        || o[0] >= 240
}

fn ipv6_is_blocked(v6: Ipv6Addr) -> bool {
    v6.is_loopback()            // ::1
        || v6.is_unspecified() // ::
        // fc00::/7 — unique local addresses.
        || (v6.segments()[0] & 0xfe00) == 0xfc00
        // fe80::/10 — link-local.
        || (v6.segments()[0] & 0xffc0) == 0xfe80
}

/// Pure SSRF policy: validate a URL plus the socket addrs it resolved to.
/// `resolved` must be the full set of addrs the connection may use (the same
/// set later pinned via `resolve`). Returns `Ok(())` only if the scheme is
/// allowed AND every resolved IP is outside the blocked ranges.
///
/// Pure and side-effect-free so it can be unit-tested directly (the host
/// path additionally resolves DNS and pins the connection to `resolved`).
fn validate_outbound_url(url: &reqwest::Url, resolved: &[SocketAddr]) -> Result<(), String> {
    let scheme = url.scheme();
    if scheme != "http" && scheme != "https" {
        return Err(format!(
            "{{\"kind\":\"url_blocked\",\"reason\":\"scheme_not_allowed\",\"scheme\":\"{scheme}\"}}"
        ));
    }
    if resolved.is_empty() {
        return Err("{\"kind\":\"url_blocked\",\"reason\":\"dns_no_addresses\"}".to_owned());
    }
    for addr in resolved {
        if ip_is_blocked(addr.ip()) {
            return Err(format!(
                "{{\"kind\":\"url_blocked\",\"reason\":\"private_or_loopback_ip\",\"ip\":\"{}\"}}",
                addr.ip()
            ));
        }
    }
    Ok(())
}

/// Resolve a URL's host to socket addrs and run the SSRF policy. Returns the
/// validated addrs (to be pinned via `resolve`) on success.
async fn resolve_and_validate(url: &reqwest::Url) -> Result<Vec<SocketAddr>, String> {
    // A literal-IP host is parsed directly (no DNS); otherwise look it up.
    let host = url
        .host_str()
        .ok_or_else(|| "{\"kind\":\"url_blocked\",\"reason\":\"missing_host\"}".to_owned())?;
    let port = url
        .port_or_known_default()
        .ok_or_else(|| "{\"kind\":\"url_blocked\",\"reason\":\"unknown_port\"}".to_owned())?;

    let resolved: Vec<SocketAddr> = if let Ok(ip) = host.parse::<IpAddr>() {
        vec![SocketAddr::new(ip, port)]
    } else {
        tokio::net::lookup_host((host, port))
            .await
            .map_err(|e| {
                format!(
                    "{{\"kind\":\"url_blocked\",\"reason\":\"dns_resolution_failed\",\"detail\":\"{e}\"}}"
                )
            })?
            .collect()
    };

    validate_outbound_url(url, &resolved)?;
    Ok(resolved)
}

/// Perform a real HTTP request using reqwest (pure-Rust, rustls-tls).
/// Returns a loom-core NetResp on success or an error string on failure.
///
/// SSRF-guarded: resolves+validates the URL (and every redirect hop) and pins
/// the connection to the validated IPs so a guest cannot reach internal
/// targets. See the SSRF-guard comment block above.
async fn do_http_request(req: NetRequest) -> Result<loom_core::vault::NetResp, String> {
    let method = reqwest::Method::from_bytes(req.method.as_bytes()).map_err(|e| e.to_string())?;
    let mut current_url = reqwest::Url::parse(&req.url).map_err(|e| e.to_string())?;

    for _hop in 0..=MAX_REDIRECT_HOPS {
        // Resolve + validate THIS hop, then pin the connection to the
        // validated addrs so reqwest cannot re-resolve to a different
        // (internal) IP between our check and the connect.
        let resolved = resolve_and_validate(&current_url).await?;
        let host = current_url
            .host_str()
            .ok_or_else(|| "{\"kind\":\"url_blocked\",\"reason\":\"missing_host\"}".to_owned())?
            .to_owned();

        let mut builder = reqwest::Client::builder()
            .use_rustls_tls()
            // Disable auto-redirect: we follow Location manually so the guard
            // re-runs on every hop.
            .redirect(reqwest::redirect::Policy::none());
        for addr in &resolved {
            builder = builder.resolve(&host, *addr);
        }
        let client = builder.build().map_err(|e| e.to_string())?;

        let mut rb = client.request(method.clone(), current_url.clone());
        for (k, v) in &req.headers {
            rb = rb.header(k.as_str(), v.as_str());
        }
        // Vault-substituted bearer token: applied AFTER the plain headers so it
        // wins over any guest-supplied Authorization value (the historical
        // overwrite-in-map semantics). `expose()` here is the single wire-out
        // site; the value never reaches Debug/Serialize (G1/TB4).
        if let Some(auth) = &req.authorization {
            rb = rb.header("Authorization", auth.expose().as_str());
        }
        if !req.body.is_empty() {
            rb = rb.body(req.body.clone());
        }

        let response = rb.send().await.map_err(|e| e.to_string())?;
        let status = response.status().as_u16();

        // Manual redirect handling: on a 3xx with a Location, validate the
        // next hop and loop; otherwise return the response.
        if response.status().is_redirection() {
            if let Some(loc) = response.headers().get(reqwest::header::LOCATION) {
                let loc = loc.to_str().map_err(|e| {
                    format!("{{\"kind\":\"url_blocked\",\"reason\":\"bad_location_header\",\"detail\":\"{e}\"}}")
                })?;
                current_url = current_url.join(loc).map_err(|e| {
                    format!("{{\"kind\":\"url_blocked\",\"reason\":\"bad_redirect_target\",\"detail\":\"{e}\"}}")
                })?;
                continue;
            }
            // 3xx without Location: nothing to follow, return as-is.
        }

        let headers: std::collections::BTreeMap<String, String> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.as_str().to_owned(), v.to_str().unwrap_or("").to_owned()))
            .collect();
        let body = response.bytes().await.map_err(|e| e.to_string())?.to_vec();

        return Ok(loom_core::vault::NetResp {
            status,
            headers,
            body,
        });
    }

    Err("{\"kind\":\"url_blocked\",\"reason\":\"too_many_redirects\"}".to_owned())
}

#[cfg(test)]
mod ssrf_guard_tests {
    use super::{ip_is_blocked, validate_outbound_url};
    use std::net::{IpAddr, SocketAddr};

    fn addr(s: &str) -> SocketAddr {
        SocketAddr::new(s.parse::<IpAddr>().unwrap(), 80)
    }

    #[test]
    fn blocks_loopback_private_linklocal_and_metadata() {
        for ip in [
            "127.0.0.1",
            "127.1.2.3",
            "10.0.0.1",
            "172.16.5.4",
            "172.31.255.255",
            "192.168.1.1",
            "169.254.169.254", // cloud metadata endpoint
            "169.254.0.1",
            "0.0.0.0",
            "100.64.0.1", // CGN/shared
            "198.18.0.1", // benchmarking
            "240.0.0.1",  // reserved
            "::1",
            "fc00::1",          // ULA
            "fd00::1",          // ULA
            "fe80::1",          // link-local
            "::ffff:127.0.0.1", // IPv4-mapped loopback (smuggling)
            "::ffff:169.254.169.254",
        ] {
            assert!(ip_is_blocked(ip.parse().unwrap()), "{ip} must be blocked");
        }
    }

    #[test]
    fn allows_public_addresses() {
        for ip in [
            "8.8.8.8",
            "1.1.1.1",
            "93.184.216.34",
            "2606:4700:4700::1111",
        ] {
            assert!(!ip_is_blocked(ip.parse().unwrap()), "{ip} must be allowed");
        }
    }

    #[test]
    fn validate_rejects_non_http_scheme() {
        let url = reqwest::Url::parse("file:///etc/passwd").unwrap();
        let err = validate_outbound_url(&url, &[addr("8.8.8.8")]).unwrap_err();
        assert!(err.contains("scheme_not_allowed"), "got: {err}");
    }

    #[test]
    fn validate_rejects_resolved_internal_ip_dns_rebind() {
        // A perfectly public-looking https URL whose host resolved (via DNS,
        // simulated here) to an internal IP must be rejected — this is the
        // DNS-rebind defense: the verdict is on the RESOLVED addr, not the
        // hostname.
        let url = reqwest::Url::parse("https://totally-public.example/").unwrap();
        let err = validate_outbound_url(&url, &[addr("169.254.169.254")]).unwrap_err();
        assert!(err.contains("private_or_loopback_ip"), "got: {err}");
        assert!(err.contains("169.254.169.254"), "names the IP: {err}");
    }

    #[test]
    fn validate_rejects_when_any_resolved_addr_is_blocked() {
        // Multi-A-record rebind: one public + one internal addr must still be
        // rejected (we'd pin all of them, so any internal one is reachable).
        let url = reqwest::Url::parse("https://mixed.example/").unwrap();
        let err = validate_outbound_url(&url, &[addr("8.8.8.8"), addr("127.0.0.1")]).unwrap_err();
        assert!(err.contains("private_or_loopback_ip"), "got: {err}");
    }

    #[test]
    fn validate_rejects_empty_resolution() {
        let url = reqwest::Url::parse("https://nxdomain.example/").unwrap();
        let err = validate_outbound_url(&url, &[]).unwrap_err();
        assert!(err.contains("dns_no_addresses"), "got: {err}");
    }

    #[test]
    fn validate_passes_public_https() {
        let url = reqwest::Url::parse("https://example.com/path").unwrap();
        assert!(validate_outbound_url(&url, &[addr("93.184.216.34")]).is_ok());
    }
}

/// Lazy-register a per-session chromium shim if it isn't already registered,
/// returning the namespaced effective `ShimId` (`chromium:<session>`).
///
/// Clones the `"chromium"` template config, sets the session-scoped
/// `LOOM_SHIM_USER_DATA_DIR`, runs `configure` (callers needing extra env —
/// e.g. `navigate_execute`'s safe-profile block — mutate the config there,
/// BEFORE register), then registers. Shared by navigate / evaluate /
/// set_input_files; each call site keeps its OWN replay-mode guard (distinct
/// error message). `shim_call` is intentionally not a caller — it resolves the
/// template id differently.
fn register_chromium_shim_if_absent(
    shim_manager: &crate::shim_manager::ShimManager,
    session_id_str: &str,
    configure: impl FnOnce(&mut crate::shim_manager::ShimConfig),
) -> Result<crate::shim_manager::ShimId, HostError> {
    use crate::shim_manager::ShimId;
    let effective_id = ShimId(format!("chromium:{}", session_id_str));
    if shim_manager.is_registered(&effective_id) {
        return Ok(effective_id);
    }
    match shim_manager
        .configs
        .get(&ShimId("chromium".to_owned()))
        .map(|c| c.clone())
    {
        Some(mut config) => {
            let dir = std::env::temp_dir().join(format!("loom-chromium-{}", session_id_str));
            config
                .env
                .push(("LOOM_SHIM_USER_DATA_DIR".into(), dir.display().to_string()));
            configure(&mut config);
            shim_manager.register(effective_id.clone(), config);
            Ok(effective_id)
        }
        None => Err(HostError::ShimFailure(
            "no template config registered for shim chromium".to_owned(),
        )),
    }
}

#[cfg(test)]
mod register_chromium_shim_tests {
    use super::{register_chromium_shim_if_absent, HostError};
    use crate::host_observability::HostObservability;
    use crate::shim_manager::{ShimConfig, ShimId, ShimManager};
    use std::sync::Arc;

    fn mgr_with_template() -> Arc<ShimManager> {
        let sm = ShimManager::new(HostObservability::new(false));
        sm.register(ShimId("chromium".to_owned()), ShimConfig::default());
        sm
    }

    #[test]
    fn registers_session_scoped_shim_with_user_data_dir() {
        let sm = mgr_with_template();
        let id = register_chromium_shim_if_absent(&sm, "sess-a", |_| {}).unwrap();
        assert_eq!(id, ShimId("chromium:sess-a".to_owned()));
        assert!(sm.is_registered(&ShimId("chromium:sess-a".to_owned())));
        let cfg = sm
            .configs
            .get(&ShimId("chromium:sess-a".to_owned()))
            .unwrap();
        assert!(cfg
            .env
            .iter()
            .any(|(k, v)| k == "LOOM_SHIM_USER_DATA_DIR" && v.contains("loom-chromium-sess-a")));
    }

    #[test]
    fn configure_closure_can_add_safe_profile_env() {
        // Mirrors navigate_execute's safe-profile block staying at the call site.
        let sm = mgr_with_template();
        register_chromium_shim_if_absent(&sm, "sess-b", |config| {
            config
                .env
                .push(("LOOM_SHIM_PROFILE".to_owned(), "safe".to_owned()));
        })
        .unwrap();
        let cfg = sm
            .configs
            .get(&ShimId("chromium:sess-b".to_owned()))
            .unwrap();
        assert!(cfg
            .env
            .iter()
            .any(|(k, v)| k == "LOOM_SHIM_PROFILE" && v == "safe"));
    }

    #[test]
    fn idempotent_when_already_registered_skips_configure() {
        let sm = mgr_with_template();
        let first = register_chromium_shim_if_absent(&sm, "sess-c", |c| {
            c.env.push(("FIRST".to_owned(), "1".to_owned()));
        })
        .unwrap();
        // Already registered → returns the same id WITHOUT re-running configure.
        let second = register_chromium_shim_if_absent(&sm, "sess-c", |c| {
            c.env.push(("SECOND".to_owned(), "2".to_owned()));
        })
        .unwrap();
        assert_eq!(first, second);
        let cfg = sm
            .configs
            .get(&ShimId("chromium:sess-c".to_owned()))
            .unwrap();
        assert!(cfg.env.iter().any(|(k, _)| k == "FIRST"));
        assert!(!cfg.env.iter().any(|(k, _)| k == "SECOND"));
    }

    #[test]
    fn missing_template_returns_shim_failure() {
        let sm = ShimManager::new(HostObservability::new(false)); // no "chromium" template
        let err = register_chromium_shim_if_absent(&sm, "sess-d", |_| {}).unwrap_err();
        assert!(matches!(err, HostError::ShimFailure(_)));
    }
}
