//! Regenerate `docs/actions.md` and the `loom.1` family of man pages
//! from the canonical action registry and the clap derive.
//!
//! Run:
//!     cargo run --example gen-docs -p loom-cli
//!
//! Output is deterministic — same registry + same clap surface produces
//! byte-identical files. CI runs this and fails if `git diff docs/`
//! is dirty.

use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use clap::CommandFactory;
use loom_cli::command_router::Cli;
use loom_rpc::action_registry::{ActionMeta, ACTIONS};

fn main() -> Result<(), Box<dyn Error>> {
    let docs_dir = repo_relative("docs");
    fs::create_dir_all(&docs_dir)?;

    write_actions_md(&docs_dir.join("actions.md"))?;
    write_man_pages(&docs_dir)?;

    println!(
        "Wrote docs/actions.md and {} man pages",
        count_man_pages(&docs_dir)?
    );
    Ok(())
}

fn repo_relative(p: &str) -> PathBuf {
    let mut out = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    out.pop();
    out.push(p);
    out
}

fn write_file_atomic(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == contents {
            return Ok(());
        }
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, contents)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

fn count_man_pages(dir: &Path) -> Result<usize, Box<dyn Error>> {
    let mut n = 0;
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        if entry.path().extension().and_then(|s| s.to_str()) == Some("1") {
            n += 1;
        }
    }
    Ok(n)
}

// ---------- docs/actions.md ----------

fn write_actions_md(path: &Path) -> Result<(), Box<dyn Error>> {
    let mut s = String::new();
    s.push_str("<!-- Generated by `cargo run --example gen-docs -p loom-cli`. DO NOT EDIT. -->\n");
    s.push_str("<!-- Source of truth: loom-rpc/src/action_registry/action_registry.rs -->\n\n");
    s.push_str("# Loom action catalogue\n\n");
    s.push_str(
        "Every JSON-RPC action loom exposes, with its parameters, return shape, \
         and a copy-pasteable example. The CI gate in [.github/workflows/ci.yml] \
         fails any PR that desyncs this file from the registry.\n\n",
    );

    s.push_str("## Index\n\n");
    let mut by_surface: BTreeMap<&str, Vec<&ActionMeta>> = BTreeMap::new();
    for a in ACTIONS {
        by_surface.entry(a.surface_prefix()).or_default().push(a);
    }
    for (surface, actions) in &by_surface {
        s.push_str(&format!("### `{surface}.*`\n\n"));
        for a in actions {
            s.push_str(&format!(
                "- [`{name}`](#{anchor}) — {summary}\n",
                name = a.name,
                anchor = anchor_for(a.name),
                summary = a.summary,
            ));
        }
        s.push('\n');
    }

    s.push_str("## Actions\n\n");
    for a in ACTIONS {
        s.push_str(&format!(
            "### <a id=\"{anchor}\"></a>`{name}`\n\n",
            anchor = anchor_for(a.name),
            name = a.name
        ));
        s.push_str(&format!("**{}**\n\n", a.summary));
        s.push_str(a.description);
        s.push_str("\n\n");

        s.push_str("**Parameters**\n\n");
        if a.params.is_empty() {
            s.push_str("_(none)_\n\n");
        } else {
            s.push_str("| Name | Type | Required | Description |\n");
            s.push_str("|------|------|----------|-------------|\n");
            for p in a.params {
                s.push_str(&format!(
                    "| `{name}` | `{ty}` | {req} | {doc} |\n",
                    name = p.name,
                    ty = p.ty,
                    req = if p.required { "required" } else { "optional" },
                    doc = escape_md_table(p.doc),
                ));
            }
            s.push('\n');
        }

        s.push_str(&format!("**Returns:** {}\n\n", a.returns));

        s.push_str("**Example**\n\n```sh\n");
        s.push_str(&render_example_shell(a));
        s.push_str("\n```\n\n");

        s.push_str("---\n\n");
    }

    // Trailing newline only once; trim any incidental extras for determinism.
    let trimmed = s.trim_end_matches('\n');
    let final_text = format!("{trimmed}\n");
    write_file_atomic(path, &final_text)?;
    Ok(())
}

fn anchor_for(name: &str) -> String {
    name.replace('.', "-")
}

fn escape_md_table(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn render_example_shell(a: &ActionMeta) -> String {
    a.example
        .iter()
        .map(|t| {
            if t.chars()
                .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '$' | '`' | '\\'))
            {
                format!("'{}'", t.replace('\'', "'\\''"))
            } else {
                t.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

// ---------- docs/loom-*.1 ----------

fn write_man_pages(out_dir: &Path) -> Result<(), Box<dyn Error>> {
    // Pin the man-page version to the package's CARGO_PKG_VERSION rather than
    // the runtime LOOM_VERSION (which includes the build-time git SHA + date,
    // and would force a man-page diff on every commit — making the CI
    // staleness gate impossible to satisfy). The shipped binary still
    // reports the full SHA-tagged version via `loom --version`; only the
    // checked-in man page uses the bare semver.
    let cmd = Cli::command()
        .name("loom")
        .version(env!("CARGO_PKG_VERSION"));
    render_man(&cmd, out_dir, "loom")?;

    let action_summaries = build_action_summaries();
    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        let sub_name = sub.get_name().to_string();
        let file = format!("loom-{sub_name}");
        // clap::Command::name takes Into<clap::builder::Str>, which requires
        // a 'static string. We're a short-lived codegen binary; intentional leak.
        let leaked: &'static str = Box::leak(file.clone().into_boxed_str());
        let sub_cmd = sub.clone().name(leaked);

        let mut buf: Vec<u8> = Vec::new();
        clap_mangen::Man::new(sub_cmd).render(&mut buf)?;
        let mut text = String::from_utf8(buf)?;

        if sub_name == "action" {
            text = append_supported_actions_section(&text, &action_summaries);
        }

        let trimmed = text.trim_end_matches('\n');
        let final_text = format!("{trimmed}\n");
        write_file_atomic(&out_dir.join(format!("{file}.1")), &final_text)?;
    }
    Ok(())
}

fn render_man(cmd: &clap::Command, out_dir: &Path, base_name: &str) -> Result<(), Box<dyn Error>> {
    let leaked: &'static str = Box::leak(base_name.to_string().into_boxed_str());
    let named = cmd.clone().name(leaked);
    let mut buf: Vec<u8> = Vec::new();
    clap_mangen::Man::new(named).render(&mut buf)?;
    let text = String::from_utf8(buf)?;
    let trimmed = text.trim_end_matches('\n');
    let final_text = format!("{trimmed}\n");
    write_file_atomic(&out_dir.join(format!("{base_name}.1")), &final_text)?;
    Ok(())
}

fn build_action_summaries() -> String {
    let mut by_surface: BTreeMap<&str, Vec<&ActionMeta>> = BTreeMap::new();
    for a in ACTIONS {
        by_surface.entry(a.surface_prefix()).or_default().push(a);
    }
    let mut out = String::new();
    out.push_str(".SH SUPPORTED ACTIONS\n");
    out.push_str(
        ".PP\n\
         Loom ships with the following registered actions. Run \
         \\fBloom action <name> --help\\fR for the full per-action signature.\n",
    );
    for (surface, actions) in &by_surface {
        out.push_str(&format!(".SS \\fB{surface}.*\\fR\n"));
        out.push_str(".TP\n");
        for a in actions {
            out.push_str(&format!(
                "\\fB{name}\\fR\n{summary}\n.TP\n",
                name = a.name,
                summary = a.summary,
            ));
        }
        // Drop trailing dangling .TP
        if out.ends_with(".TP\n") {
            out.truncate(out.len() - ".TP\n".len());
        }
    }
    out
}

fn append_supported_actions_section(man: &str, supported: &str) -> String {
    let mut combined = man.trim_end_matches('\n').to_string();
    combined.push('\n');
    combined.push_str(supported);
    combined
}
