"""
Schema-driven SDK generation drift test.

When `schemas/v1.json` changes, the Python and TypeScript SDK
surfaces must be regenerated by the codegen tool — no hand-drift
permitted. This test fails if the SDK source on disk doesn't match
what running the codegen would produce.
"""
from __future__ import annotations

import importlib
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from tests.conftest import MockDaemon, SCHEMA_REGISTRY


SDK_ROOT = Path(__file__).parent.parent
LOOM_PKG = SDK_ROOT / "loom"
CODEGEN_MODULE = "loom._codegen"


def test_codegen_produces_types_from_daemon_schema(daemon: MockDaemon, tmp_path: Path):
    """Codegen script connects to daemon, calls rpc.schemas(), writes types.py."""
    output = tmp_path / "types.py"
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            CODEGEN_MODULE,
            "--socket",
            str(daemon.socket_path),
            "--token",
            daemon.token,
            "--output",
            str(output),
        ],
        capture_output=True,
        text=True,
        cwd=str(SDK_ROOT),
    )
    assert result.returncode == 0, f"codegen failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    assert output.exists(), "codegen did not write output file"
    content = output.read_text()
    assert "SessionCreate" in content or "session_create" in content or "session.create" in content or "SessionInfo" in content, (
        "generated types.py does not reference any expected type"
    )


def test_codegen_types_match_committed_snapshot(daemon: MockDaemon, tmp_path: Path):
    """
    Generated types.py is consistent when schema unchanged.
    Running codegen twice produces the same output.
    """
    out1 = tmp_path / "types1.py"
    out2 = tmp_path / "types2.py"

    for output in (out1, out2):
        result = subprocess.run(
            [
                sys.executable, "-m", CODEGEN_MODULE,
                "--socket", str(daemon.socket_path),
                "--token", daemon.token,
                "--output", str(output),
            ],
            capture_output=True,
            text=True,
            cwd=str(SDK_ROOT),
        )
        assert result.returncode == 0

    assert out1.read_text() == out2.read_text(), (
        "codegen is non-deterministic: two runs with same schema produced different output"
    )


def test_codegen_detects_schema_change(daemon: MockDaemon, tmp_path: Path):
    """When daemon returns an updated schema, codegen produces different types.py."""
    out_before = tmp_path / "before.py"
    out_after = tmp_path / "after.py"

    # First codegen against default schema
    result = subprocess.run(
        [
            sys.executable, "-m", CODEGEN_MODULE,
            "--socket", str(daemon.socket_path),
            "--token", daemon.token,
            "--output", str(out_before),
        ],
        capture_output=True, text=True, cwd=str(SDK_ROOT),
    )
    assert result.returncode == 0

    # Modify daemon schema to add a new method
    import copy
    new_registry = copy.deepcopy(SCHEMA_REGISTRY)
    new_registry["methods"].append({
        "method": "session.newmethod",
        "request": {"type": "object", "properties": {"x": {"type": "string"}}},
        "response": {"type": "object", "properties": {"y": {"type": "string"}}},
    })
    new_registry["source_wit_sha256"] = "00112233" * 8
    daemon.register_handler("rpc.schemas", lambda _: new_registry)

    result = subprocess.run(
        [
            sys.executable, "-m", CODEGEN_MODULE,
            "--socket", str(daemon.socket_path),
            "--token", daemon.token,
            "--output", str(out_after),
        ],
        capture_output=True, text=True, cwd=str(SDK_ROOT),
    )
    assert result.returncode == 0

    assert out_before.read_text() != out_after.read_text(), (
        "codegen produced identical output despite schema change — hand-drift risk"
    )


# ─── Hand-written admin types drift guard ────────────────────────────────
# The new admin RPC wrappers (kill_session, daemon_health) bypass codegen
# (BUILTIN_CORE-style validation-bypass per the original prompt); their
# result types are HAND-WRITTEN in `python-sdk/loom/types.py`. This guard
# catches camelCase / snake_case drift between the Rust Server struct
# (snake_case JSON output) and the Python dataclass field names.
#
# It does NOT compile Rust source — it parses the source text via regex.
# Rust struct file: ../../loom-rpc/src/rpc_handlers/rpc_handlers.rs
# Python types file: ../loom/types.py


def _extract_rust_struct_fields(rs_path: Path, struct_name: str) -> set[str]:
    """Cheap regex extraction of `pub field_name: ` fields from a Rust
    struct block. Skips field-less generic-only structs."""
    import re

    src = rs_path.read_text()
    # Find `pub struct StructName {` ... `}` block.
    m = re.search(
        rf"pub struct {re.escape(struct_name)}\s*\{{(.*?)\n\}}",
        src,
        re.DOTALL,
    )
    if not m:
        return set()
    body = m.group(1)
    return set(re.findall(r"^\s*pub\s+([a-z_]\w*)\s*:", body, re.MULTILINE))


def _extract_python_dataclass_fields(py_path: Path, class_name: str) -> set[str]:
    """Cheap extraction of dataclass field names from a Python source.

    Slices from `class Name:` to the next `class ` (or EOF), then collects
    indented `field_name: TypeHint` lines while skipping docstring blocks
    and blank lines.
    """
    import re

    src = py_path.read_text()
    m = re.search(rf"class {re.escape(class_name)}\b[^:]*:\s*\n", src)
    if not m:
        return set()
    rest = src[m.end():]
    # Cut off at next top-level definition.
    cut = re.search(r"^(class |def |\w)", rest, re.MULTILINE)
    body = rest[: cut.start()] if cut else rest
    # Strip docstring block (line starting with `    """` and continuing
    # until closing `"""`).
    body = re.sub(r'(?ms)^\s+""".*?"""\s*$', "", body)
    return set(re.findall(r"^\s+([a-z_]\w*)\s*:", body, re.MULTILINE))


def test_handwritten_admin_types_field_drift():
    """Hand-written ShimDeepHealth in types.py must match Rust struct fields."""
    rs_path = (
        Path(__file__).parent.parent.parent
        / "loom-rpc"
        / "src"
        / "rpc_handlers"
        / "rpc_handlers.rs"
    )
    py_path = Path(__file__).parent.parent / "loom" / "_admin_types.py"
    if not rs_path.exists():
        pytest.skip("Rust source not co-located (running from installed wheel?)")
    if not py_path.exists():
        pytest.skip("Python _admin_types.py not found")

    # ShimDeepHealth: hand-written; check field names align.
    rust_fields = _extract_rust_struct_fields(rs_path, "ShimDeepHealth")
    py_fields = _extract_python_dataclass_fields(py_path, "ShimDeepHealth")
    assert py_fields, "ShimDeepHealth dataclass missing from _admin_types.py"
    assert rust_fields == py_fields, (
        f"ShimDeepHealth field drift between Rust and Python:\n"
        f"  Rust only: {rust_fields - py_fields}\n"
        f"  Py only:   {py_fields - rust_fields}\n"
    )
    # Also check ShimBreakerSnapshot (already existed on Rust side; we
    # added a hand-written mirror for symmetry).
    rust_breaker = _extract_rust_struct_fields(rs_path, "ShimBreakerSnapshot")
    py_breaker = _extract_python_dataclass_fields(py_path, "ShimBreakerSnapshot")
    assert rust_breaker == py_breaker, (
        f"ShimBreakerSnapshot field drift:\n"
        f"  Rust only: {rust_breaker - py_breaker}\n"
        f"  Py only:   {py_breaker - rust_breaker}\n"
    )
