// module_kind: wit-bindgen-generated
//
// GuestBindings — `wit-bindgen` Rust guest-side export trait + impl
// stub for the `web-surface` interface declared in
// `wit/loom-surface.wit`. **This file is machine-generated at build time.**
// The real surface crate's `OUT_DIR/bindings.rs` shadows this; we keep
// this file as the human-readable contract surface for review.
//
// # wit-bindgen invocation (emitted by build.rs)
//
// ```ignore
// wit_bindgen::generate!({
//     world: "surface",
//     path: "../../wit/loom-surface.wit",
//     exports: { "loom:surface/web-surface": WebSurfaceImpl },
// });
// ```
//
// # Contract semantics
// - **Sole WASM export.** `web-surface` interface is the only export
//   from `loom-surface-web.wasm` (BC-SURF-02; IC-SURF-12). v1.5 surface
//   crates each export their own world (shell-surface, fs-surface,
//   api-surface, native-surface).
// - **10 verb methods.** One method per WIT-defined verb on
//   `web-surface`. `WebSurfaceImpl::<verb>` delegates to the
//   corresponding verb module's `execute` function (IC-SURF-12 +
//   SR-SURF-01).
// - **No business logic.** Pure delegation; the trait body is the only
//   place where the verb dispatch table lives. Adding an 11th verb
//   requires a WIT change + regen.
// - **No mode awareness (SR-SURF-05).** The bytecode this file produces
//   is identical between live and replay; the host swaps the linker.
//
// # Banned in this module (BC-SURF-04)
// - All the usual platform-symbol bans apply; here doubly so because
//   GuestBindings is the WASM export boundary.


extern crate alloc;

use crate::click_verb::click_verb::{ClickAction, ClickVerb};
use crate::error_mapper::error_mapper::HostError;
use crate::evaluate_verb::evaluate_verb::{EvaluateAction, EvaluateVerb};
use crate::hover_verb::hover_verb::{HoverAction, HoverVerb};
use crate::navigate_verb::navigate_verb::{NavigateAction, NavigateVerb};
use crate::receipt_builder::receipt_builder::Receipt;
use crate::screenshot_verb::screenshot_verb::{ScreenshotAction, ScreenshotVerb};
use crate::scroll_verb::scroll_verb::{ScrollAction, ScrollVerb};
use crate::select_verb::select_verb::{SelectAction, SelectVerb};
use crate::snapshot_verb::snapshot_verb::{SnapshotAction, SnapshotVerb};
use crate::type_text_verb::type_text_verb::{TypeTextAction, TypeTextVerb};
use crate::wait_verb::wait_verb::{WaitAction, WaitVerb};

/// The `web-surface` WIT export trait (mirrors the WIT interface).
/// Generated by `wit-bindgen`; the trait shape is determined by WIT.
pub trait WebSurface {
    fn navigate(a: NavigateAction) -> Result<Receipt, HostError>;
    fn click(a: ClickAction) -> Result<Receipt, HostError>;
    fn type_text(a: TypeTextAction) -> Result<Receipt, HostError>;
    fn select(a: SelectAction) -> Result<Receipt, HostError>;
    fn hover(a: HoverAction) -> Result<Receipt, HostError>;
    fn scroll(a: ScrollAction) -> Result<Receipt, HostError>;
    fn wait(a: WaitAction) -> Result<Receipt, HostError>;
    fn evaluate(a: EvaluateAction) -> Result<Receipt, HostError>;
    fn screenshot(a: ScreenshotAction) -> Result<Receipt, HostError>;
    fn snapshot(a: SnapshotAction) -> Result<Receipt, HostError>;
}

/// The unit struct that implements `WebSurface`. Each method delegates
/// directly to the corresponding verb module's `execute` — pure
/// dispatch, no logic.
pub struct WebSurfaceImpl;

impl WebSurface for WebSurfaceImpl {
    fn navigate(a: NavigateAction) -> Result<Receipt, HostError> {
        NavigateVerb::execute(a)
    }
    fn click(a: ClickAction) -> Result<Receipt, HostError> {
        ClickVerb::execute(a)
    }
    fn type_text(a: TypeTextAction) -> Result<Receipt, HostError> {
        TypeTextVerb::execute(a)
    }
    fn select(a: SelectAction) -> Result<Receipt, HostError> {
        SelectVerb::execute(a)
    }
    fn hover(a: HoverAction) -> Result<Receipt, HostError> {
        HoverVerb::execute(a)
    }
    fn scroll(a: ScrollAction) -> Result<Receipt, HostError> {
        ScrollVerb::execute(a)
    }
    fn wait(a: WaitAction) -> Result<Receipt, HostError> {
        WaitVerb::execute(a)
    }
    fn evaluate(a: EvaluateAction) -> Result<Receipt, HostError> {
        EvaluateVerb::execute(a)
    }
    fn screenshot(a: ScreenshotAction) -> Result<Receipt, HostError> {
        ScreenshotVerb::execute(a)
    }
    fn snapshot(a: SnapshotAction) -> Result<Receipt, HostError> {
        SnapshotVerb::execute(a)
    }
}

/// Compile-time enumeration of the 10 verb names exported from the
/// `web-surface` WIT interface. Used by integration tests +
/// `tools/lint-surface-bindings.py` to assert WIT-vs-impl agreement
/// (SR-SURF-01).
pub const WEB_SURFACE_VERBS: &[&str] = &[
    "navigate",
    "click",
    "type-text",
    "select",
    "hover",
    "scroll",
    "wait",
    "evaluate",
    "screenshot",
    "snapshot",
];
