#!/usr/bin/env python3
"""
test_lint_no_platform_imports.py — verification test for the
companion `lint_no_platform_imports.py` (W7.5).

Per A-W8 / FND-0040 / D40 the lint silently scanned zero files for the
entire v0.9.3 release because `SCAN_DIRS` pointed at a non-existent
`src/<crate>/src` layout. To stop that regression from recurring, this
script plants a deliberate violation under `loom-core/src/_lint_fixture.rs`,
invokes the lint, and asserts it exits non-zero. The fixture is removed
in `finally` so the working tree is always clean.

Exit 0 → lint correctly caught the planted violation (success).
Exit 1 → lint did NOT catch it (the path bug regressed, or the rule set
         got narrower) — the wider CI gate must fail loud.

Wire from `.github/workflows/ci.yml` like:
    - name: Verify no-platform-imports lint catches violations
      run: python3 scripts/test_lint_no_platform_imports.py
"""

import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
LOOM_ROOT = SCRIPT_DIR.parent
LINT_SCRIPT = SCRIPT_DIR / "lint_no_platform_imports.py"
FIXTURE_PATH = LOOM_ROOT / "loom-core" / "src" / "_lint_fixture.rs"
# Use a banned exact symbol from the lint's list. `Foundation` is the
# loudest macOS-only marker — any false-positive review would catch a
# bug here, not at the operator's fingertips.
FIXTURE_BODY = """// AUTO-GENERATED by scripts/test_lint_no_platform_imports.py — DO NOT COMMIT
// If you see this file checked in, the verification test crashed before
// `finally` cleanup; delete it and re-run.
use Foundation;
fn _planted() {}
"""


def main() -> int:
    if not LINT_SCRIPT.exists():
        print(f"FAIL: {LINT_SCRIPT} does not exist", file=sys.stderr)
        return 1
    if FIXTURE_PATH.exists():
        print(
            f"FAIL: {FIXTURE_PATH} already exists; refusing to overwrite a "
            "stale fixture from a prior crashed run. Inspect + delete it manually.",
            file=sys.stderr,
        )
        return 1

    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    try:
        FIXTURE_PATH.write_text(FIXTURE_BODY)
        result = subprocess.run(
            [sys.executable, str(LINT_SCRIPT)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print(
                "FAIL: lint_no_platform_imports.py returned 0 despite a "
                "planted `Foundation` import — SCAN_DIRS path bug regressed.",
                file=sys.stderr,
            )
            print(f"  stdout: {result.stdout!r}", file=sys.stderr)
            print(f"  stderr: {result.stderr!r}", file=sys.stderr)
            return 1
        # The lint must specifically name our fixture in its output.
        marker = "_lint_fixture.rs"
        if marker not in result.stderr:
            print(
                "FAIL: lint exited non-zero but did NOT mention "
                f"`{marker}` in stderr — the scan may be hitting a different "
                "violation; verify the lint logic.",
                file=sys.stderr,
            )
            print(f"  stderr: {result.stderr!r}", file=sys.stderr)
            return 1
        print(
            "OK: lint_no_platform_imports.py correctly caught the planted "
            "violation."
        )
        return 0
    finally:
        try:
            FIXTURE_PATH.unlink()
        except FileNotFoundError:
            pass
        # Clean up `__pycache__`/empty parent dirs that might have been
        # created — best effort; never raise.
        cache = FIXTURE_PATH.parent / "__pycache__"
        if cache.is_dir():
            shutil.rmtree(cache, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
