// AuthMiddleware — HELLO-token handshake.
//
// # Contract semantics
// - **First-message contract .** The client's first frame
//   MUST be `HELLO {token}` (a single space-separated string).
//   Mismatch, missing, or wrong-shape → close connection with
//   `LoomErrorCode::ProtocolAuthRequired`. No retry on the same
//   connection.
// - **Per-startup token .** Token generated by `OsRng` at
//   `SocketServer::new` and printed once on stdout. Mandatory rotation
//   on daemon restart. Token type is opaque `Token(String)`.
// - **Idle timeout in `AwaitingHello` (5s default).** Enforced by the
//   caller (`ConnectionHandler`) via `tokio::time::timeout`; if the
//   client sends no bytes within 5s the connection is dropped silently.
// - **No state retained.** Verifier holds only the daemon token via
//   `Arc<Token>`; per-connection state lives in `ConnectionHandler`.

use crate::error_translator::error_translator::JsonRpcError;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::Duration;

/// Opaque per-startup daemon token. Generated by `OsRng` (32 bytes,
/// hex-encoded). Constant-time compared on validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Token(pub String);

/// Default idle timeout in `AwaitingHello` state per design.md §4 row.
pub const HELLO_IDLE_TIMEOUT: Duration = Duration::from_secs(5);

/// Parsed HELLO message. Constructed by `AuthMiddleware::parse_hello`
/// from the first frame's bytes.
#[derive(Debug, Clone)]
pub struct HelloMessage {
    pub token: Token,
}

#[derive(Debug)]
pub enum AuthError {
    /// First frame was not a `HELLO {token}` line.
    Malformed,
    /// Token did not match the daemon's startup token.
    TokenMismatch,
    /// No frame received within `HELLO_IDLE_TIMEOUT`.
    Timeout,
}

/// Trait surface so `ConnectionHandler` can be tested with a fake
/// middleware that always passes / always fails.
pub trait AuthMiddlewareApi: Send + Sync {
    /// Parse the first frame's bytes into a `HelloMessage`. Returns
    /// `AuthError::Malformed` if the bytes are not `HELLO <token>`.
    fn parse_hello(&self, frame: &[u8]) -> Result<HelloMessage, AuthError>;

    /// Validate the parsed token against the daemon's per-startup token.
    /// On mismatch returns `AuthError::TokenMismatch`.
    fn validate_hello(&self, msg: &HelloMessage) -> Result<(), AuthError>;

    /// Translate an `AuthError` into the `LoomErrorCode::ProtocolAuthRequired`
    /// envelope sent to the client immediately before connection close.
    fn auth_error_to_envelope(&self, err: AuthError) -> JsonRpcError;
}

pub struct AuthMiddleware {
    pub(crate) daemon_token: Arc<Token>,
}

impl AuthMiddleware {
    /// Construct from the per-startup daemon token. The `Arc` is
    /// shared across all per-connection tasks.
    pub fn new(daemon_token: Arc<Token>) -> Arc<Self> {
        Arc::new(Self { daemon_token })
    }
}
