// Re-export of the locked Phase 5.3 interface. DO NOT EDIT here.
// Edit `systems/loom-cli/modules/ActionCommands/interfaces.rs` instead.
// ActionCommands — unified handler for `loom action <surface>.<verb>`.
//
// # Contract semantics
// - **IC-CLI-03.** Every `action <surface>.<verb>` invocation maps to
//   exactly one RPC call: `<surface>.<verb>` (e.g. `web.click`).
// - **Schema-validated full params BEFORE RPC.** `dispatch` assembles
//   the complete params object (session + extra args), reads the request
//   schema from `SchemaCache`, and validates the assembled object; on
//   validation failure, returns `CliError::Usage` (exit 2) BEFORE any
//   socket I/O.  Validation uses the full object so `required: [session]`
//   constraints in web-action schemas are satisfied (AC-AVOR-01).
// - **SR-CLI-03 (receipt pass-through).** The receipt's
//   `serde_json::Value` flows to `OutputFormatter::write` verbatim.
// - **IC-CLI-09 (help parity).** `--help` text is generated by
//   `HelpGenerator` from the same schema; clap arg names are
//   mechanically derived from JSON-Schema field names.

use clap::Args;
use serde::{Deserialize, Serialize};

use crate::cli_config::CliConfig;
use crate::rpc_client::RpcClient;
use crate::schema_cache::SchemaCache;
use crate::CliError;

/// Free-form passthrough args. The `<surface>.<verb>` argument is
/// required positional; remaining `--key value` pairs are collected
/// into `extra` and validated against the schema at dispatch time.
#[derive(Debug, Clone, Args, Serialize, Deserialize)]
pub struct ActionArgs {
    /// `<surface>.<verb>` (e.g. `web.click`).
    pub method: String,
    /// `--session SID` is required by all action methods.
    #[arg(long)]
    pub session: String,
    /// Remaining `--key value` pairs gathered as raw strings; validated
    /// against the JSON-Schema for `method` before RPC dispatch.
    #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
    pub extra: Vec<String>,
}

/// Dispatch entrypoint. Assembles the full params object (session + extra),
/// performs schema validation, then exactly one RPC call, then writes the
/// receipt verbatim.
///
/// NOTE: `session` is merged into `full_params` BEFORE `validate_args` is
/// called.  Web-action schemas declare `session` as a required property; if
/// we validated `extra_params` alone the call would always fail with
/// '"session" is a required property' (AC-AVOR-01).
pub async fn dispatch(
    rpc: &RpcClient,
    schemas: &SchemaCache,
    cfg: &CliConfig,
    args: ActionArgs,
) -> Result<(), CliError> {
    // Pull the request schema (if available) so parse_extra_to_json can
    // coerce values to the property's declared type instead of greedily
    // auto-coercing to integer/float. Without this, a `--text 5551234`
    // for a `string`-typed field becomes a JSON Number and the local
    // schema validator rejects it as "5551234 is not of type 'string'".
    let property_types = schemas
        .request_schema(&args.method)
        .map(extract_property_types)
        .unwrap_or_default();
    let extra_params = parse_extra_to_json_typed(&args.extra, &property_types)?;
    let mut full_params = serde_json::Map::new();
    full_params.insert(
        "session".to_string(),
        serde_json::Value::String(args.session.clone()),
    );
    if let serde_json::Value::Object(m) = extra_params {
        full_params.extend(m);
    }
    let full_params = serde_json::Value::Object(full_params);
    validate_args(schemas, &args.method, &full_params)?;
    // Canonicalise the method name before the wire call so observability
    // (request logs, replay, rpc.schemas method labels) sees only the
    // canonical form. Aliases (e.g. `web.type_text` → `web.type`) are
    // a syntactic shim for backward compat (AC-CLIROUTE-02); they must
    // not leak through to downstream layers.
    let canonical_method = loom_shared::action_aliases::canonicalise(&args.method);
    // URL scheme allowlist check (AC-URLSEC-01 through AC-URLSEC-06).
    // Runs after schema validation (URL is a valid string) and before RPC,
    // satisfying IC-CLI-03 (rejected URLs never reach rpc.call).
    if canonical_method == "web.navigate" {
        if let Some(url) = full_params.get("url").and_then(|v| v.as_str()) {
            let scheme_check = crate::url_allowlist::check_url_scheme(url);
            if let Err(CliError::Receipt(ref v)) = scheme_check {
                // Print JSON receipt to stdout (mirrors the success receipt path).
                // print_error in main uses eprintln! (stderr) — no double-stdout.
                println!(
                    "{}",
                    crate::output_formatter::format_output(v, cfg.pretty).unwrap_or_default()
                );
            }
            scheme_check?;
        }
    }
    let resp = rpc.call(canonical_method, full_params).await?;
    println!(
        "{}",
        crate::output_formatter::format_output(&resp, cfg.pretty)?
    );
    // AC-CLIEXIT-01: receipts with status="error" raise to exit 1, even
    // when the JSON-RPC envelope was a successful result. SR-CLI-03 is
    // preserved — the receipt is already on stdout above.
    crate::error_mapper::receipt_to_result(resp).map(|_| ())
}

/// Parses `extra` (a `Vec<String>` of `--key value ...`) into a JSON
/// object. Pure function; lives here so the validation flow is fully
/// schema-driven and callable from interface tests.
///
/// Rules:
/// - `--key value` (where `value` does not start with `--`) → string or
///   auto-coerced JSON number / bool.
/// - `--flag` with no following value (EOF or next arg starts with `--`)
///   → `true` (boolean flag).
/// - Repeated keys: last write wins.
///
/// Schema-blind shortcut for callers that don't have a schema handy
/// (interface tests, ad-hoc consumers). The dispatch path uses
/// `parse_extra_to_json_typed` so a `string`-typed property doesn't
/// silently get coerced to a Number when the user types digits.
pub fn parse_extra_to_json(extra: &[String]) -> Result<serde_json::Value, CliError> {
    parse_extra_to_json_typed(extra, &std::collections::HashMap::new())
}

/// Schema-aware variant. `property_types` maps property name → declared
/// JSON-schema "type" string ("string", "integer", "boolean", "number",
/// etc.). When a hint is present:
///   - "string": preserve the raw value verbatim, no number coercion.
///   - "integer"/"number": parse, falling back to string only if parse
///     fails (preserving the original error path).
///   - "boolean": parse "true"/"false" literally; anything else stays
///     a string (lets the validator surface the violation).
/// When no hint is present, fall back to the legacy auto-coerce
/// (preserves the AC-CLI-02.1 behavior tests pin).
pub fn parse_extra_to_json_typed(
    extra: &[String],
    property_types: &std::collections::HashMap<String, String>,
) -> Result<serde_json::Value, CliError> {
    let mut map = serde_json::Map::new();
    let mut i = 0;
    while i < extra.len() {
        let s = &extra[i];
        let key = s
            .strip_prefix("--")
            .ok_or_else(|| CliError::Usage(format!("unexpected positional argument: {}", s)))?;
        let value = if let Some(next) = extra.get(i + 1) {
            if !next.starts_with("--") {
                i += 1;
                coerce_with_hint(next, property_types.get(key).map(String::as_str))
            } else {
                serde_json::Value::Bool(true)
            }
        } else {
            serde_json::Value::Bool(true)
        };
        map.insert(key.to_string(), value);
        i += 1;
    }
    Ok(serde_json::Value::Object(map))
}

/// Coerce a raw string value into JSON, preferring the schema-declared
/// type when known. Falls back to the legacy auto-coerce ladder
/// (i64 → f64 → bool literal → string) when the property is unhinted.
fn coerce_with_hint(raw: &str, hint: Option<&str>) -> serde_json::Value {
    match hint {
        Some("string") => serde_json::Value::String(raw.to_string()),
        Some("integer") => raw
            .parse::<i64>()
            .map(|n| serde_json::Value::Number(serde_json::Number::from(n)))
            .unwrap_or_else(|_| serde_json::Value::String(raw.to_string())),
        Some("number") => raw
            .parse::<f64>()
            .ok()
            .and_then(serde_json::Number::from_f64)
            .map(serde_json::Value::Number)
            .unwrap_or_else(|| serde_json::Value::String(raw.to_string())),
        Some("boolean") => match raw {
            "true" => serde_json::Value::Bool(true),
            "false" => serde_json::Value::Bool(false),
            other => serde_json::Value::String(other.to_string()),
        },
        // No hint → legacy auto-coerce ladder.
        _ => {
            if let Ok(n) = raw.parse::<i64>() {
                serde_json::Value::Number(serde_json::Number::from(n))
            } else if let Ok(f) = raw.parse::<f64>() {
                serde_json::Number::from_f64(f)
                    .map(serde_json::Value::Number)
                    .unwrap_or_else(|| serde_json::Value::String(raw.to_string()))
            } else if raw == "true" {
                serde_json::Value::Bool(true)
            } else if raw == "false" {
                serde_json::Value::Bool(false)
            } else {
                serde_json::Value::String(raw.to_string())
            }
        }
    }
}

/// Extract `{property_name: type_string}` from a JSON-schema's
/// `request.properties` object. Returns an empty map if the schema
/// shape doesn't match. Multi-type values (e.g. `["string", "null"]`)
/// resolve to the first non-`null` entry so a Nullable<String> is
/// still treated as a string.
pub fn extract_property_types(
    schema: &serde_json::Value,
) -> std::collections::HashMap<String, String> {
    let mut out = std::collections::HashMap::new();
    let Some(props) = schema.get("properties").and_then(|v| v.as_object()) else {
        return out;
    };
    for (name, prop) in props {
        let ty = match prop.get("type") {
            Some(serde_json::Value::String(s)) => Some(s.clone()),
            Some(serde_json::Value::Array(items)) => items
                .iter()
                .find_map(|v| v.as_str().filter(|s| *s != "null").map(String::from)),
            _ => None,
        };
        if let Some(t) = ty {
            out.insert(name.clone(), t);
        }
    }
    out
}

/// Validates the assembled JSON args against the request schema for
/// `method`. Returns `CliError::Usage` on mismatch.
pub fn validate_args(
    schemas: &SchemaCache,
    method: &str,
    args: &serde_json::Value,
) -> Result<(), CliError> {
    let Some(schema) = schemas.request_schema(method) else {
        let mut available: Vec<&str> = schemas.methods().collect();
        available.sort_unstable();
        let list = if available.is_empty() {
            "(none — run loom postinstall to load schemas)".to_string()
        } else {
            available.join(", ")
        };
        return Err(CliError::Usage(format!(
            "unknown method: {method}. Available: {list}"
        )));
    };
    let compiled = jsonschema::Validator::new(schema)
        .map_err(|e| CliError::Internal(format!("schema compile error: {e}")))?;
    if !compiled.is_valid(args) {
        let errors: Vec<String> = compiled.iter_errors(args).map(|e| e.to_string()).collect();
        return Err(CliError::Usage(format!(
            "invalid args for {method}: {}",
            errors.join(", ")
        )));
    }
    Ok(())
}
