.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH loom-serve 1  "loom-serve " 
.SH NAME
loom\-serve \- Spawn the daemon. RPC\-free local action
.SH SYNOPSIS
\fBloom\-serve\fR [\fB\-\-socket\fR] [\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Spawn the daemon. RPC\-free local action
.SH OPTIONS
.TP
\fB\-\-socket\fR \fI<SOCKET>\fR

.TP
\fB\-\-config\fR \fI<CONFIG>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
