.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH loom-postinstall 1  "loom-postinstall " 
.SH NAME
loom\-postinstall \- Idempotent installer. RPC\-free local action (IC\-CLI\-06)
.SH SYNOPSIS
\fBloom\-postinstall\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Idempotent installer. RPC\-free local action (IC\-CLI\-06)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
