.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH loom-doctor 1  "loom-doctor " 
.SH NAME
loom\-doctor \- Health checks. RPC\-free local action (IC\-CLI\-07)
.SH SYNOPSIS
\fBloom\-doctor\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Health checks. RPC\-free local action (IC\-CLI\-07)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
