"""
Python types for the loom SDK.

This file is generated by ``python -m loom._codegen`` from the daemon's
``rpc.schemas()`` response. Do not edit by hand — run codegen to regenerate.

Generated from: loom-rpc SchemaRegistry (rpc.schemas() endpoint)
Source WIT: wit/loom-surface.wit

Types mirror the wire types in:
  - systems/loom-rpc/modules/core_service_adapter/interfaces.rs
  - systems/loom-rpc/modules/host_service_adapter/interfaces.rs
  - systems/loom-rpc/modules/error_translator/interfaces.rs
"""

# GENERATED — do not edit by hand. Run: python -m loom._codegen
from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class LoomErrorCode(StrEnum):
    """Stable error codes mirroring LoomErrorCode in loom-rpc (BC-RPC-03)."""

    protocol_auth_required = "protocol_auth_required"
    protocol_malformed = "protocol_malformed"
    schema_violation = "schema_violation"
    method_not_found = "method_not_found"
    session_not_found = "session_not_found"
    session_aborted = "session_aborted"
    budget_exceeded = "budget_exceeded"
    surface_trap = "surface_trap"
    surface_unavailable = "surface_unavailable"
    vault_grant_not_found = "vault_grant_not_found"
    vault_grant_revoked = "vault_grant_revoked"
    vault_credential_type_unsupported = "vault_credential_type_unsupported"
    store_integrity_failed = "store_integrity_failed"
    internal_error = "internal_error"


@dataclass
class SessionInfo:
    """Response type for session.create / session.close / session.abort."""

    session_id: str
    status: str
    created_at_ms: int

    @classmethod
    def _from_dict(cls, d: dict) -> SessionInfo:
        return cls(
            session_id=d["session_id"],
            status=d["status"],
            created_at_ms=d.get("created_at_ms", 0),
        )


@dataclass
class SessionInspection:
    """Response type for session.inspect."""

    session_id: str
    at_action: int | None
    manifest_summary: dict

    @classmethod
    def _from_dict(cls, d: dict) -> SessionInspection:
        return cls(
            session_id=d["session_id"],
            at_action=d.get("at_action"),
            manifest_summary=d.get("manifest_summary", {}),
        )


@dataclass
class DiffReport:
    """Response type for session.diff."""

    a: str
    b: str
    diff: dict

    @classmethod
    def _from_dict(cls, d: dict) -> DiffReport:
        return cls(a=d["a"], b=d["b"], diff=d.get("diff", {}))


@dataclass
class ExportInfo:
    """Response type for session.export."""

    session_id: str
    format: str
    artifact_ref: str

    @classmethod
    def _from_dict(cls, d: dict) -> ExportInfo:
        return cls(
            session_id=d["session_id"],
            format=d["format"],
            artifact_ref=d.get("artifact_ref", ""),
        )


@dataclass
class ValidationResult:
    """Response type for session.validate."""

    session_id: str
    passed: bool
    reasons: list[str]

    @classmethod
    def _from_dict(cls, d: dict) -> ValidationResult:
        return cls(
            session_id=d["session_id"],
            passed=d.get("passed", False),
            reasons=d.get("reasons", []),
        )


@dataclass
class GrantInfo:
    """Response type for vault.grant. Contains grant_id only — no secrets."""

    grant_id: str
    origin: str
    scopes: list[str]
    ttl_seconds: int
    label: str

    @classmethod
    def _from_dict(cls, d: dict) -> GrantInfo:
        return cls(
            grant_id=d["grant_id"],
            origin=d.get("origin", ""),
            scopes=d.get("scopes", []),
            ttl_seconds=d.get("ttl_seconds", 0),
            label=d.get("label", ""),
        )


@dataclass
class Receipt:
    """Action receipt returned by action.web.* methods (WIT receipt record)."""

    action_hash: str
    outcome_hash: str
    emitted_at_ms: int
    # settle-capture: readiness mode the capture was gated on
    # ("load" | "networkidle" | "settled"). Present on navigate receipts;
    # None for verbs without a readiness gate.
    settle_until: str | None = None
    # settle-capture: how the readiness wait ended
    # ("reached" | "timeout" | "dom_unstable"). "timeout"/"dom_unstable" mean
    # the bounded fallback fired (persistent connection / perpetual animation)
    # — the page never reached the requested readiness state.
    settle_outcome: str | None = None

    @classmethod
    def _from_dict(cls, d: dict) -> Receipt:
        return cls(
            action_hash=d.get("action_hash", ""),
            outcome_hash=d.get("outcome_hash", ""),
            emitted_at_ms=d.get("emitted_at_ms", 0),
            settle_until=d.get("settle_until"),
            settle_outcome=d.get("settle_outcome"),
        )


@dataclass
class MethodSchema:
    """One method's request + response schemas from rpc.schemas()."""

    method: str
    request: dict
    response: dict

    @classmethod
    def _from_dict(cls, d: dict) -> MethodSchema:
        return cls(method=d["method"], request=d.get("request", {}), response=d.get("response", {}))


@dataclass
class SchemaRegistry:
    """Response type for rpc.schemas()."""

    methods: list[MethodSchema]
    source_wit_sha256: str

    @classmethod
    def _from_dict(cls, d: dict) -> SchemaRegistry:
        return cls(
            methods=[MethodSchema._from_dict(m) for m in d.get("methods", [])],
            source_wit_sha256=d.get("source_wit_sha256", ""),
        )
