//! `wit_type_marshaller` — WIT↔Rust type bridge + wasmtime component
//! model bindings. The `loom_surface_bindings` module is generated by
//! `wasmtime::component::bindgen!` from `wit/loom-surface.wit`.
pub mod wit_type_marshaller;
pub use wit_type_marshaller::*;

/// Generated WIT bindings. `loom_surface_bindings::host::Host` is the
/// trait `HostState` implements; `add_to_linker` registers it with a
/// `wasmtime::component::Linker<HostState>`.
pub mod loom_surface_bindings {
    wasmtime::component::bindgen!({
        world: "surface",
        path: "../wit/loom-surface.wit",
        // async: true was removed in wasmtime 44; use imports/exports options instead.
        imports: { default: async },
    });
}

#[cfg(test)]
mod interface_tests;
